Repository graphhopper/graphhopper, pull requests merged in 2018-02, with the labels that each got.

#1286 Improve release management
  .travis.yml
  android/app/pom.xml
  client-hc/pom.xml
  client-hc/src/test/java/com/graphhopper/api/GraphHopperMatrixGoogleIT.java
  core/files/settings.xml
  core/pom.xml
  pom.xml
  reader-gtfs/pom.xml
  reader-json/pom.xml
  reader-osm/pom.xml
  reader-shp/pom.xml
  tools/pom.xml
  web/pom.xml
Labels: architecture, improvement

#1278 Added Extent and OsmKey to Geocoding
  client-hc/src/main/java/com/graphhopper/api/model/GHGeocodingEntry.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperGeocodingIT.java
Labels: improvement

#1295 Rollback maven version for now
  .travis.yml
Labels: architecture, bug

#1294 simplify also when instructions disabled
  core/src/main/java/com/graphhopper/util/PathSimplification.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: improvement
