Repository graphhopper/graphhopper, pull requests merged in 2018-04, with the labels that each got.

#1331 serve static content from disc instead from classpath
  docs/core/quickstart-from-source.md
  graphhopper.sh
  web/pom.xml
  web/src/main/java/com/graphhopper/http/GraphHopperDebugApplication.java
Labels: bug

#1340 allow "false" in addition to "no", fixes #1337
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
Labels: bug

#1339 Issue 1305 - Distance Details
  core/src/main/java/com/graphhopper/util/Parameters.java
  core/src/main/java/com/graphhopper/util/details/DistanceDetails.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
Labels: improvement

#1348 added fullscreen button
  .gitignore
  web/src/main/resources/assets/css/style.css
  web/src/main/resources/assets/img/full-reverse.png
  web/src/main/resources/assets/img/full-reverse.svg
  web/src/main/resources/assets/img/full.png
  web/src/main/resources/assets/img/full.svg
  web/src/main/resources/assets/js/main.js
  web/src/main/resources/assets/js/map.js
Labels: new feature, web
