Repository graphhopper/graphhopper, pull requests merged in 2018-10, with the labels that each got.

#1476 Makes parameters available to CH classes via PMap.
  api/src/main/java/com/graphhopper/util/PMap.java
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/CHParameters.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
Labels: refactoring

#1481 Removes Weighting from PrepareContractionHierarchies constructor.
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
Labels: improvement, refactoring

#1482 Accept cattle grid #1479
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
Labels: improvement, osm

#1484 Move reader-shp into separate repository
  README.md
  pom.xml
  reader-shp/pom.xml
  reader-shp/src/main/java/com/graphhopper/reader/shp/GraphHopperSHP.java
  reader-shp/src/main/java/com/graphhopper/reader/shp/OSMShapeFileReader.java
  reader-shp/src/main/java/com/graphhopper/reader/shp/ShapeFileReader.java
  reader-shp/src/main/java/com/graphhopper/reader/shp/Utils.java
  reader-shp/src/test/java/com/graphhopper/reader/shp/ShapeFileReaderTest.java
  reader-shp/src/test/resources/data/gis.osm_roads_free_1.cpg
  reader-shp/src/test/resources/data/gis.osm_roads_free_1.dbf
  reader-shp/src/test/resources/data/gis.osm_roads_free_1.prj
  reader-shp/src/test/resources/data/gis.osm_roads_free_1.shp
  reader-shp/src/test/resources/data/gis.osm_roads_free_1.shx
  reader-shp/src/test/resources/data/malta-latest.osm.pbf
  reader-shp/src/test/resources/log4j.xml
Labels: refactoring

#1488 Allows using less ch weightings than loaded, fixes #1413.
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
Labels: improvement
