Repository graphhopper/graphhopper, pull requests merged in 2018-05, with the labels that each got.

#1300 Fix download issue if SRTM files misses '.' before 'hgt'
  core/src/main/java/com/graphhopper/reader/dem/AbstractSRTMElevationProvider.java
  core/src/test/java/com/graphhopper/reader/dem/SRTMProviderTest.java
Labels: bug

#1357 Fix lint errors in webapp
  .codeclimate.yml
  docs/core/deploy.md
  web/.jshintignore
  web/package.json
  web/src/main/assembly/zip.xml
  web/src/main/resources/assets/js/config/tileLayers.js
  web/src/main/resources/assets/js/graphhopper/GHRequest.js
  web/src/main/resources/assets/js/main-template.js
  web/src/main/resources/assets/js/main.js
  web/src/main/resources/assets/js/tools/url.js
Labels: improvement, web

#1362 Fix missing vertical bar for elevation
  web/src/main/resources/assets/css/leaflet.elevation-0.0.4.css
Labels: web

#1361 Update example for GTFS reader
  reader-gtfs/README.md
Labels: documentation

#1358 Update Leaflet to 1.3.1, enable autoPan on markers
  web/package.json
  web/src/main/resources/assets/css/flatpickr.min.css
  web/src/main/resources/assets/css/leaflet.css
  web/src/main/resources/assets/index.html
  web/src/main/resources/assets/js/instructions.js
  web/src/main/resources/assets/js/main-template.js
  web/src/main/resources/assets/js/main.js
  web/src/main/resources/assets/js/map.js
Labels: improvement, web

#1327 include jdk10
  .travis.yml
  core/src/main/java/com/graphhopper/coll/GHTreeMapComposed.java
  pom.xml
Labels: architecture

#1365 added documentation for intellij
  docs/core/images/intellij-run-config.png
  docs/core/quickstart-from-source.md
Labels: documentation

#1381 Reduce usages of fwd/bwd flags in DefaultEdgeFilter constructor
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/AbstractRoutingAlgorithm.java
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/ch/NodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/util/DefaultEdgeFilter.java
  core/src/main/java/com/graphhopper/storage/change/ChangeGraphHelper.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndex.java
  core/src/test/java/com/graphhopper/reader/PrincetonReaderTest.java
  core/src/test/java/com/graphhopper/routing/PathBidirRefTest.java
  core/src/test/java/com/graphhopper/routing/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphEdgeIdFinderTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/index/AbstractLocationIndexTester.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
  core/src/test/java/com/graphhopper/util/CHEdgeIteratorTest.java
  core/src/test/java/com/graphhopper/util/DepthFirstSearchTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphExplorer.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GtfsReader.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
Labels: refactoring
