Repository graphhopper/graphhopper, pull requests merged in 2018-06, with the labels that each got.

#1399 Adds instructions how to increase heap memory limit to quickstart docs.
  docs/core/quickstart-from-source.md
  docs/web/quickstart.md
Labels: documentation

#1390 Exception Mapping
  web-api/src/main/java/com/graphhopper/MultiException.java
  web-api/src/main/java/com/graphhopper/jackson/GraphHopperModule.java
  web-api/src/main/java/com/graphhopper/jackson/MultiExceptionSerializer.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/http/MultiExceptionGPXMessageBodyWriter.java
  web-bundle/src/main/java/com/graphhopper/http/MultiExceptionMapper.java
  web-bundle/src/main/java/com/graphhopper/http/TypeGPXFilter.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web/pom.xml
  web/src/main/java/com/graphhopper/http/GraphHopperApplication.java
Labels: improvement

#1406 Made point hint matching stricter and avoid problems for short street names
  core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
  core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
Labels: bug

#1303 (WIP) Isochrone documentation
  docs/index.md
  docs/isochrone/java.md
  docs/web/api-doc.md
Labels: documentation
