Repository graphhopper/graphhopper, pull requests merged in 2019-03, with the labels that each got.

#1455 Replaces truncation with rounding when setting edge distance or CH shortcut weight.
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
Labels: improvement

#1570 trying cleaner enums again
  core/src/main/java/com/graphhopper/routing/VirtualEdgeIterator.java
  core/src/main/java/com/graphhopper/routing/VirtualEdgeIteratorState.java
  core/src/main/java/com/graphhopper/routing/profiles/EncodedValueLookup.java
  core/src/main/java/com/graphhopper/routing/profiles/EnumEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/IndexBased.java
  core/src/main/java/com/graphhopper/routing/profiles/ObjectEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/RoadClass.java
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/profiles/EnumEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/profiles/MappedObjectEncodedValueTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphSupport.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/WrapperGraph.java
Labels: refactoring

#1575 Fix typo
  docs/core/weighting.md
Labels: documentation

#1569 Use Leaflet.Heightgraph to show PathDetails
  web/package.json
  web/src/main/resources/assets/css/L.Control.Heightgraph.css
  web/src/main/resources/assets/css/images/area-chart.svg
  web/src/main/resources/assets/css/images/remove.svg
  web/src/main/resources/assets/css/leaflet.elevation-0.0.4.css
  web/src/main/resources/assets/index.html
  web/src/main/resources/assets/js/lib/leaflet.elevation-0.0.4.min.js
  web/src/main/resources/assets/js/main-template.js
  web/src/main/resources/assets/js/main.js
  web/src/main/resources/assets/js/map.js
Labels: new feature, web

#1581 Fixes wrong routing occurring when stall on demand is used with virtual via-nodes.
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionCH.java
  core/src/main/java/com/graphhopper/routing/VirtualEdgeIterator.java
  core/src/main/java/com/graphhopper/storage/index/QueryResult.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceIssue1574Test.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: bug

#1541 Cannot set a blocked edge to accessible again
  core/src/main/java/com/graphhopper/storage/change/ChangeGraphHelper.java
  core/src/test/java/com/graphhopper/storage/change/ChangeGraphHelperTest.java
  core/src/test/resources/com/graphhopper/storage/change/overlaydata2.json
  core/src/test/resources/com/graphhopper/storage/change/overlaydata3.json
Labels: improvement

#1587 Android: VTM 0.11.0 OpenGL vector map library
  android/app/build.gradle
  android/app/pom.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: android
