Repository graphhopper/graphhopper, pull requests merged in 2019-01, with the labels that each got.

#1510 Speed up query and preparation for CH
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/DAType.java
  core/src/main/java/com/graphhopper/storage/GHDirectory.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
Labels: improvement

#1515 changes nickname
  CONTRIBUTORS.md
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionCH.java
Labels: architecture

#1518 Removes dir parameter from PrepareContractionHierarchies constructor.
  core/src/main/java/com/graphhopper/routing/ch/AbstractNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
Labels: refactoring

#1531 Do not create loop-edges
  client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java
  core/src/main/java/com/graphhopper/routing/util/EdgeFilter.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/Isochrone.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
  reader-osm/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops.xml
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: bug
