Repository graphhopper/graphhopper, pull requests merged in 2019-04, with the labels that each got.

#1586 Fixes some issues with turn cost times.
  core/src/main/java/com/graphhopper/routing/PathBidirRef.java
  core/src/main/java/com/graphhopper/routing/util/TurnCostEncoder.java
  core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/util/PathMerger.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/PathBidirRefTest.java
  core/src/test/java/com/graphhopper/routing/weighting/TurnWeightingTest.java
Labels: bug

#1594 Update documentation regarding usage of EncodingManager's constructor
  docs/core/low-level-api.md
  docs/core/routing.md
Labels: documentation, improvement

#1596 Fixes edge-based CH problem with u-turns at virtual edges, fixes #1593
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
  core/src/main/java/com/graphhopper/storage/TurnCostExtension.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
Labels: bug

#1485 add LocationIndexTree.query(BBox)
  api/src/main/java/com/graphhopper/util/shapes/BBox.java
  api/src/main/java/com/graphhopper/util/shapes/Circle.java
  api/src/main/java/com/graphhopper/util/shapes/Polygon.java
  api/src/main/java/com/graphhopper/util/shapes/Shape.java
  api/src/test/java/com/graphhopper/util/shapes/BBoxTest.java
  api/src/test/java/com/graphhopper/util/shapes/CircleTest.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDFullIndex.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDFullWithEdgesIndex.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDQuadtree.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndex.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/EmptyLocationIndex.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
  web-bundle/src/main/java/com/graphhopper/resources/PtIsochroneResource.java
Labels: algorithm, new feature

#1600 Android: VTM 0.11.1 OpenGL vector map library
  android/app/build.gradle
  android/app/pom.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: android

#1603 Extracts new ShortcutUnpacker from Path4CH.
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/Path4CH.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
  core/src/main/java/com/graphhopper/storage/ShortcutUnpacker.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
Labels: improvement, refactoring
