Repository graphhopper/graphhopper, pull requests merged in 2019-05, with the labels that each got.

#1606 Fixes missing best path update for bidir algos when there is a loop at the meeting point (#1592)
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/util/TraversalMode.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionTest.java
  core/src/test/java/com/graphhopper/routing/AStarTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionRefTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraTest.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/util/GHUtilityTest.java
  reader-gtfs/pom.xml
Labels: algorithm, refactoring

#1611 Implements correct time calculation for edge-based CH.
  api/src/main/java/com/graphhopper/util/Helper.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/Path.java
  core/src/main/java/com/graphhopper/routing/PathBidirRef.java
  core/src/main/java/com/graphhopper/routing/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedPathCH.java
  core/src/main/java/com/graphhopper/routing/ch/Path4CH.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
  core/src/main/java/com/graphhopper/storage/Graph.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/ShortcutUnpacker.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphSupport.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/RealtimeFeed.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/WrapperGraph.java
Labels: bug

#1614 Route pedestrians over highway=platform, define it as a pushing section for bikes. Unit testing considerations.
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
Labels: bug

#1612 Remove unnecessary check if way has at least two nodes
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
Labels: improvement

#1624 Makes QueryGraph's edge-explorer cache work for all EdgeFilters, fixes #1623.
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/main/java/com/graphhopper/routing/util/DefaultEdgeFilter.java
  core/src/test/java/com/graphhopper/routing/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
  core/src/test/java/com/graphhopper/storage/GraphEdgeIdFinderTest.java
Labels: bug, improvement
