Repository graphhopper/graphhopper, pull requests merged in 2019-12, with the labels that each got.

#1811 Remove FlagEncoder.getAnnotation
  core/src/main/java/com/graphhopper/reader/ReaderElement.java
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
  core/src/main/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactory.java
  core/src/main/java/com/graphhopper/routing/profiles/GetOffBike.java
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParser.java
  core/src/main/java/com/graphhopper/util/PathMerger.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsFromEdges.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/MountainBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParserTest.java
  core/src/test/java/com/graphhopper/util/InstructionListTest.java
  core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/TripFromLabel.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  web-bundle/src/test/java/com/graphhopper/util/gpx/GpxFromInstructionsTest.java
Labels: refactoring

#1816 Enforce non-CH graphs for all LocationIndex implementations
  core/src/main/java/com/graphhopper/storage/index/Location2IDFullIndex.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDFullWithEdgesIndex.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDQuadtree.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeCHTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
Labels: refactoring

#1814 more instruction annotations and bug fix
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/resources/com/graphhopper/util/ar.txt
  core/src/main/resources/com/graphhopper/util/ast.txt
  core/src/main/resources/com/graphhopper/util/bg.txt
  core/src/main/resources/com/graphhopper/util/ca.txt
  core/src/main/resources/com/graphhopper/util/cs_CZ.txt
  core/src/main/resources/com/graphhopper/util/da_DK.txt
  core/src/main/resources/com/graphhopper/util/de_DE.txt
  core/src/main/resources/com/graphhopper/util/el.txt
  core/src/main/resources/com/graphhopper/util/en_US.txt
  core/src/main/resources/com/graphhopper/util/eo.txt
  core/src/main/resources/com/graphhopper/util/es.txt
  core/src/main/resources/com/graphhopper/util/fa.txt
  core/src/main/resources/com/graphhopper/util/fi.txt
  core/src/main/resources/com/graphhopper/util/fil.txt
  core/src/main/resources/com/graphhopper/util/fr_CH.txt
  core/src/main/resources/com/graphhopper/util/fr_FR.txt
  core/src/main/resources/com/graphhopper/util/gl.txt
  core/src/main/resources/com/graphhopper/util/he.txt
  core/src/main/resources/com/graphhopper/util/hr_HR.txt
  core/src/main/resources/com/graphhopper/util/hsb.txt
  core/src/main/resources/com/graphhopper/util/hu_HU.txt
  core/src/main/resources/com/graphhopper/util/in_ID.txt
  core/src/main/resources/com/graphhopper/util/it.txt
  core/src/main/resources/com/graphhopper/util/ja.txt
  core/src/main/resources/com/graphhopper/util/ko.txt
  core/src/main/resources/com/graphhopper/util/lt_LT.txt
  core/src/main/resources/com/graphhopper/util/ne.txt
  core/src/main/resources/com/graphhopper/util/nl.txt
  core/src/main/resources/com/graphhopper/util/pl_PL.txt
  core/src/main/resources/com/graphhopper/util/pt_BR.txt
  core/src/main/resources/com/graphhopper/util/pt_PT.txt
  core/src/main/resources/com/graphhopper/util/ro.txt
  core/src/main/resources/com/graphhopper/util/ru.txt
  core/src/main/resources/com/graphhopper/util/sk.txt
  core/src/main/resources/com/graphhopper/util/sl_SI.txt
  core/src/main/resources/com/graphhopper/util/sr_RS.txt
  core/src/main/resources/com/graphhopper/util/sv_SE.txt
  core/src/main/resources/com/graphhopper/util/tr.txt
  core/src/main/resources/com/graphhopper/util/uk.txt
  core/src/main/resources/com/graphhopper/util/vi_VN.txt
  core/src/main/resources/com/graphhopper/util/zh_CN.txt
  core/src/main/resources/com/graphhopper/util/zh_HK.txt
  core/src/main/resources/com/graphhopper/util/zh_TW.txt
  core/src/test/java/com/graphhopper/util/InstructionListTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: navigation, new feature

#1817 make day for conditional tag parsing configurable
  benchmark/benchmark.sh
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalOSMTagInspector.java
  core/src/main/java/com/graphhopper/reader/osm/conditional/DateRange.java
  core/src/main/java/com/graphhopper/reader/osm/conditional/DateRangeParser.java
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/Car4WDFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/test/java/com/graphhopper/reader/osm/conditional/DateRangeParserTest.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
Labels: improvement

#1819 Take routing algorithm factory out of `PrepareContractionHierarchies`
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/BidirRoutingAlgorithm.java
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/CHRoutingAlgorithmFactory.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/weighting/BidirectionalRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
Labels: refactoring

#1824 Integrate PT
  core/src/main/java/com/graphhopper/GraphHopper.java
  reader-gtfs/src/main/java/com/conveyal/gtfs/TripPatternKey.java
  reader-gtfs/src/main/java/com/conveyal/gtfs/util/Deduplicator.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphHopperGtfs.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GtfsStorage.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/PtRouteResource.java
  reader-gtfs/src/test/java/com/graphhopper/AnotherAgencyIT.java
  reader-gtfs/src/test/java/com/graphhopper/ExtendedRouteTypeIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperGtfsIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
  reader-gtfs/src/test/java/com/graphhopper/PtRouteResourceIT.java
  reader-gtfs/src/test/java/com/graphhopper/RealtimeIT.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
  web-bundle/src/main/java/com/graphhopper/http/PtRedirectFilter.java
  web-bundle/src/main/java/com/graphhopper/http/health/GraphHopperStorageHealthCheck.java
  web-bundle/src/main/java/com/graphhopper/resources/InfoResource.java
  web-bundle/src/main/java/com/graphhopper/resources/PtIsochroneResource.java
  web/src/main/java/com/graphhopper/http/cli/ImportCommand.java
  web/src/main/resources/assets/js/main-template.js
  web/src/test/java/com/graphhopper/http/resources/GtfsTest.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/PtIsochroneTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
Labels: public transport, refactoring

#1826 Remove DataFlagEncoder
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
  core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/DefaultFlagEncoderFactory.java
  core/src/main/java/com/graphhopper/routing/util/FlagEncoderFactory.java
  core/src/main/java/com/graphhopper/routing/weighting/GenericWeighting.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/weighting/GenericWeightingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageForDataFlagEncoderTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
Labels: refactoring

#1834 GH Maps: enable turn costs
  web-bundle/src/main/java/com/graphhopper/resources/InfoResource.java
  web/src/main/resources/assets/js/graphhopper/GHRequest.js
  web/src/main/resources/assets/js/main-template.js
Labels: improvement, web

#1837 (Almost) move access flag checks into weighting for CH preparation
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedWitnessPathSearcher.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareCHEdgeIteratorImpl.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareCHGraph.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIterator.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/util/CHEdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
Labels: refactoring
