Repository graphhopper/graphhopper, pull requests merged in 2019-08, with the labels that each got.

#1661 Adds new fail-fast option to hand-crafted matrix client.
  api/src/main/java/com/graphhopper/util/exceptions/DetailedIllegalArgumentException.java
  client-hc/src/main/java/com/graphhopper/api/GHMRequest.java
  client-hc/src/main/java/com/graphhopper/api/GHMatrixAbstractRequester.java
  client-hc/src/main/java/com/graphhopper/api/GHMatrixBatchRequester.java
  client-hc/src/main/java/com/graphhopper/api/GHMatrixSyncRequester.java
  client-hc/src/main/java/com/graphhopper/api/MatrixResponse.java
  client-hc/src/test/java/com/graphhopper/api/AbstractGHMatrixWebTester.java
  client-hc/src/test/java/com/graphhopper/api/AbstractGraphHopperMatrixWebIntegrationTester.java
  client-hc/src/test/resources/com/graphhopper/api/matrix-connection-not-found-fail-fast.json
  client-hc/src/test/resources/com/graphhopper/api/matrix-point-not-found-fail-fast.json
  core/src/main/java/com/graphhopper/storage/index/QueryResult.java
Labels: new feature

#1693 Remove shortcut(a, b) method from CHGraph
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeCHTest.java
Labels: refactoring

#1696 Throw error if edge_based=true, but encoder does not support turn costs
  core/src/main/java/com/graphhopper/GraphHopper.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: improvement

#1671 Identifies CH graphs by new CHProfile class instead of Weighting.
  .travis.yml
  android/app/pom.xml
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/CHProfile.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/AbstractRoutingAlgorithmTester.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraOneToManyTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  core/src/test/java/com/graphhopper/routing/ch/CHAlgoFactoryDecoratorTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/ch/WitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
  core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  core/src/test/java/com/graphhopper/util/CHEdgeIteratorTest.java
  core/src/test/java/com/graphhopper/util/GHUtilityTest.java
  reader-gtfs/pom.xml
  reader-osm/pom.xml
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  tools/pom.xml
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
Labels: refactoring

#1705 Do not consider turn cost support of other encoders when selecting traversal mode
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: bug

#1704 Add support for hgv toll sub-categories
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMTollParser.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMTollParserTest.java
Labels: improvement
