Repository graphhopper/graphhopper, pull requests merged in 2019-11, with the labels that each got.

#1711 Add support for various hazmat tags
  config-example.yml
  core/src/main/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactory.java
  core/src/main/java/com/graphhopper/routing/profiles/Hazmat.java
  core/src/main/java/com/graphhopper/routing/profiles/HazmatWater.java
  core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatWaterParser.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatWaterParserTest.java
Labels: improvement

#1759 Implement importAndClose API
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
  web/src/main/java/com/graphhopper/http/cli/ImportCommand.java
Labels: improvement

#1783 Remove GraphExtension interface
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraphTurnExt.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIterator.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
  core/src/main/java/com/graphhopper/routing/util/TestAlgoCollector.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/ExtendedNodeAccess.java
  core/src/main/java/com/graphhopper/storage/GHNodeAccess.java
  core/src/main/java/com/graphhopper/storage/Graph.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphExtension.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/NodeAccess.java
  core/src/main/java/com/graphhopper/storage/TurnCostExtension.java
  core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/reader/dem/EdgeElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionTest.java
  core/src/test/java/com/graphhopper/routing/AStarTest.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteTest.java
  core/src/test/java/com/graphhopper/routing/BidirPathExtractorTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionRefTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraTest.java
  core/src/test/java/com/graphhopper/routing/DirectedBidirectionalDijkstraTest.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/WitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMAlgoFactoryDecoratorTest.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/template/RoundTripRoutingTemplateTest.java
  core/src/test/java/com/graphhopper/routing/weighting/BidirectionalRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/TurnWeightingTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  core/src/test/java/com/graphhopper/storage/TurnCostExtensionTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphSupport.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/RealtimeFeed.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/WrapperGraph.java
  reader-gtfs/src/test/java/com/graphhopper/reader/gtfs/GraphExplorerTest.java
  reader-gtfs/src/test/java/com/graphhopper/reader/gtfs/WrapperGraphTest.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
Labels: refactoring

#1794 Moves segment size setting of graphs into constructor
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/GraphStorage.java
  core/src/test/java/com/graphhopper/GraphHopperAPITest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageForDataFlagEncoderTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/storage/GraphStorageViaMMapTest.java
Labels: refactoring

#1784 String index
  NOTICE.md
  api/src/main/java/com/graphhopper/util/AngleCalc.java
  core/src/main/java/com/graphhopper/search/NameIndex.java
  core/src/main/java/com/graphhopper/search/StringIndex.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/DataAccess.java
  core/src/main/java/com/graphhopper/storage/MMapDataAccess.java
  core/src/main/java/com/graphhopper/storage/RAMDataAccess.java
  core/src/main/java/com/graphhopper/storage/RAMIntDataAccess.java
  core/src/main/java/com/graphhopper/storage/StorableProperties.java
  core/src/main/java/com/graphhopper/storage/UnsafeDataAccess.java
  core/src/main/java/com/graphhopper/util/BitUtilBig.java
  core/src/main/java/com/graphhopper/util/BitUtilLittle.java
  core/src/main/java/com/graphhopper/util/Constants.java
  core/src/test/java/com/graphhopper/search/NameIndexTest.java
  core/src/test/java/com/graphhopper/search/StringIndexTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/DataAccessTest.java
  core/src/test/java/com/graphhopper/storage/RAMIntDataAccessTest.java
Labels: new feature

#1789 Use precompiled Pattern instances
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/parsers/helpers/OSMValueExtractor.java
Labels: improvement

#1795 Remove unnecessary slight turns
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/test/java/com/graphhopper/util/InstructionListTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: navigation

#1782 Speed up path simplification with path details/instructions
  api/src/main/java/com/graphhopper/util/PointList.java
  api/src/main/java/com/graphhopper/util/ShallowImmutablePointList.java
  core/src/main/java/com/graphhopper/util/DouglasPeucker.java
  core/src/main/java/com/graphhopper/util/PathMerger.java
  core/src/main/java/com/graphhopper/util/PathSimplification.java
  core/src/test/java/com/graphhopper/util/DouglasPeuckerTest.java
  core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: navigation, refactoring

#1797 make CHProfile selection pluggable
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/CHProfileSelector.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
Labels: refactoring

#1802 Speed up path simplification with path details/instructions - fixed
  api/src/main/java/com/graphhopper/util/PointList.java
  core/src/main/java/com/graphhopper/util/DouglasPeucker.java
  core/src/main/java/com/graphhopper/util/PathMerger.java
  core/src/main/java/com/graphhopper/util/PathSimplification.java
  core/src/test/java/com/graphhopper/util/DouglasPeuckerTest.java
  core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: improvement, navigation, refactoring

#1798 remove FlagEncoder from PathDetailsBuilderFactory
  core/src/main/java/com/graphhopper/util/PathMerger.java
  core/src/main/java/com/graphhopper/util/details/AverageSpeedDetails.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsFromEdges.java
  core/src/main/java/com/graphhopper/util/details/TimeDetails.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: refactoring

#1806 Decouple CH edge iterators from base graph edge iterators
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
Labels: refactoring

#1804 Avoid throwing NumberFormatException in the OSMValueExtractor
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxHeightParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxLengthParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWidthParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/helpers/OSMValueExtractor.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMValueExtractorTest.java
Labels: osm, refactoring

#1809 Close mmap for ElevationProvider if not removed
  core/src/main/java/com/graphhopper/reader/dem/AbstractSRTMElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/AbstractTiffElevationProvider.java
  core/src/main/java/com/graphhopper/storage/Directory.java
  core/src/main/java/com/graphhopper/storage/GHDirectory.java
Labels: improvement
