Repository graphhopper/graphhopper, pull requests merged in 2019-07, with the labels that each got.

#1654 Don't show the heightgraph on small screens
  web/package.json
  web/src/main/resources/assets/js/map.js
Labels: web

#1644 avoid snapping to a certain road class or environment
  api/src/main/java/com/graphhopper/GHRequest.java
  api/src/main/java/com/graphhopper/util/Parameters.java
  client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/util/SnapPreventionEdgeFilter.java
  core/src/main/java/com/graphhopper/util/details/DistanceDetails.java
  core/src/main/java/com/graphhopper/util/details/EdgeIdDetails.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  core/src/main/java/com/graphhopper/util/details/StreetNameDetails.java
  core/src/main/java/com/graphhopper/util/details/TimeDetails.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/routing/util/SnapPreventionEdgeFilterTest.java
  core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
  docs/web/api-doc.md
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/resources/MVTResource.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: new feature

#1664 do stricter version check in GraphHopperStorage.loadExisting
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
Labels: bug

#1656 Ignore unknown properties of spatial rules
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
Labels: improvement

#1667 Replaces some == NO_EDGE comparisons with isValid calls.
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/WitnessPathSearcher.java
  core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
  core/src/main/java/com/graphhopper/storage/TurnCostExtension.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMTurnRelation.java
Labels: refactoring

#1660 use staticHashCode to fix problems on Android but could occur elsewhere
  core/src/main/java/com/graphhopper/routing/profiles/EnumEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/UnsignedDecimalEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/UnsignedIntEncodedValue.java
Labels: bug

#1651 Response as GeoJSON
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web/src/test/java/com/graphhopper/http/isochrone/IsochroneResourceTest.java
Labels: improvement

#1669 Replaces GraphHopperStorage#getGraph(Class) with getCHGraph().
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/AbstractRoutingAlgorithmTester.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/ch/WitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeCHTest.java
  core/src/test/java/com/graphhopper/util/CHEdgeIteratorTest.java
  core/src/test/java/com/graphhopper/util/GHUtilityTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
Labels: refactoring
