Repository graphhopper/graphhopper, pull requests merged in 2019-09, with the labels that each got.

#1714 Add Kurviger Liberty and remove old Openmapsurfer Tiles
  web/src/main/resources/assets/js/config/options.js
  web/src/main/resources/assets/js/config/tileLayers.js
Labels: improvement, web

#1706 Choose edge-based CH if it was prepared and the `edge_based` parameter was not set
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: improvement

#1672 Allows setting finite u-turn costs.
  api/src/main/java/com/graphhopper/util/Parameters.java
  config-example.yml
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/CHProfileSelectionException.java
  core/src/main/java/com/graphhopper/routing/ch/CHProfileSelector.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
  core/src/main/java/com/graphhopper/storage/CHProfile.java
  core/src/main/java/com/graphhopper/storage/TurnCostExtension.java
  core/src/main/java/com/graphhopper/util/Constants.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHAlgoFactoryDecoratorTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHProfileSelectorTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/WitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/TurnWeightingTest.java
  core/src/test/java/com/graphhopper/storage/CHProfileTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  docs/core/turn-restrictions.md
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
Labels: new feature

#1718 make parsing in prepareName for point_hint faster
  core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
  core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
Labels: bug

#1719 Remove distances from CH shortcuts
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
  core/src/main/java/com/graphhopper/util/Constants.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeCHTest.java
Labels: improvement

#1720 Update issue templates
  .github/ISSUE_TEMPLATE.md
  README.md
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE/bug_report.md
  docs/core/quickstart-from-source.md
  docs/core/translations.md
  docs/index.md
Labels: documentation, improvement

#1724 WIP: Add new `turn_costs=true/false` routing parameter
  api/src/main/java/com/graphhopper/util/Parameters.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
Labels: improvement

#1662 Adds logging to exception mappers.
  web-bundle/src/main/java/com/graphhopper/http/IllegalArgumentExceptionMapper.java
  web-bundle/src/main/java/com/graphhopper/http/MultiExceptionMapper.java
  web/src/main/java/com/graphhopper/http/GHJerseyViolationExceptionMapper.java
Labels: improvement

#1729 Android: VTM 0.12.0 OpenGL vector map library
  android/app/build.gradle
  android/app/pom.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: android

#1730 Move path extraction logic out of `Path` class
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/AStar.java
  core/src/main/java/com/graphhopper/routing/AStarBidirectionCH.java
  core/src/main/java/com/graphhopper/routing/AStarBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/AlternativeRoute.java
  core/src/main/java/com/graphhopper/routing/BidirPathExtractor.java
  core/src/main/java/com/graphhopper/routing/Dijkstra.java
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/DijkstraOneToMany.java
  core/src/main/java/com/graphhopper/routing/Path.java
  core/src/main/java/com/graphhopper/routing/PathBidirRef.java
  core/src/main/java/com/graphhopper/routing/PathExtractor.java
  core/src/main/java/com/graphhopper/routing/PathNative.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedCHBidirPathExtractor.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedPathCH.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedCHBidirPathExtractor.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionTest.java
  core/src/test/java/com/graphhopper/routing/BidirPathExtractorTest.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/Isochrone.java
Labels: refactoring

#1733 Fix sort corrupting graph
  CONTRIBUTORS.md
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/test/java/com/graphhopper/util/GHUtilityTest.java
Labels: bug

#1697 Add new 'curb_side' parameter, allow specifying start/target edges
  api/src/main/java/com/graphhopper/GHRequest.java
  api/src/main/java/com/graphhopper/util/AngleCalc.java
  api/src/main/java/com/graphhopper/util/Parameters.java
  api/src/test/java/com/graphhopper/util/AngleCalcTest.java
  client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/DirectionResolver.java
  core/src/main/java/com/graphhopper/routing/DirectionResolverResult.java
  core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/RoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/test/java/com/graphhopper/routing/DirectedBidirectionalDijkstraTest.java
  core/src/test/java/com/graphhopper/routing/DirectionResolverOnQueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/DirectionResolverTest.java
  core/src/test/java/com/graphhopper/routing/template/RoundTripRoutingTemplateTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: new feature

#1740 Minor changes to developer quick start
  docs/core/quickstart-from-source.md
Labels: documentation, improvement
