Repository graphhopper/graphhopper, pull requests merged in 2019-02, with the labels that each got.

#1534 Allows reusing CH node ordering.
  core/src/main/java/com/graphhopper/routing/ch/ManualPrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/ch/NodeOrderingProvider.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
Labels: algorithm, improvement

#1535 trying to fix problems with incorrectly mapped loop edges
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops2.xml
  reader-osm/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops3.xml
  reader-osm/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops4.xml
Labels: improvement, osm

#1133 Added documentation for change graph feature
  docs/core/change-graph.md
  docs/index.md
Labels: documentation

#1436 Access refactoring
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/Car4WDFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/TagParser.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/AccessValue.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/DefaultSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/AustriaSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/GermanySpatialRule.java
  core/src/main/java/com/graphhopper/routing/weighting/GenericWeighting.java
  core/src/test/java/com/graphhopper/reader/dem/BridgeElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/reader/dem/TunnelElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/routing/profiles/DecimalEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
  core/src/test/java/com/graphhopper/routing/util/Bike2WeightFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/Car4WDFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/HikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/MotorcycleFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/MountainBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupArrayTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  core/src/test/java/com/graphhopper/routing/weighting/GenericWeightingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageForDataFlagEncoderTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
  core/src/test/java/com/graphhopper/util/InstructionListTest.java
  core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/PtFlagEncoder.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
Labels: refactoring

#1547 Adds gitinfo properties file containing git hash used when building.
  core/pom.xml
  core/src/main/resources/com/graphhopper/gitinfo
Labels: improvement

#1542 Edge CH speedup
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/ch/WitnessPathSearcher.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
  core/src/main/java/com/graphhopper/storage/Graph.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphSupport.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/RealtimeFeed.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/WrapperGraph.java
Labels: algorithm, improvement

#1555 Improves error message in case of forgotten/wrong edge_based=true/false parameter.
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
Labels: improvement

#1556 Fixes virtual edge way geometry in case of Position.PILLAR.
  core/src/main/java/com/graphhopper/routing/QueryGraph.java
  core/src/test/java/com/graphhopper/routing/QueryGraphTest.java
Labels: bug
