Repository graphhopper/graphhopper, pull requests merged in 2019-06, with the labels that each got.

#1635 Includes default u-turn cost in time calculation, fixes #1585.
  core/src/main/java/com/graphhopper/routing/PathBidirRef.java
  core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/weighting/TurnWeightingTest.java
Labels: bug

#1572 Render vector tiles from graph storage
  README.md
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
  isochrone/pom.xml
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/MVTResource.java
  web/package.json
  web/src/main/resources/assets/js/config/tileLayers.js
  web/src/main/resources/assets/js/main.js
  web/src/main/resources/assets/js/map.js
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
Labels: new feature, web

#1627 rename implementations of IntEncodedValue and DecimalEncodedValue
  core/src/main/java/com/graphhopper/routing/profiles/DecimalEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/EnumEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/IntEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/MaxHeight.java
  core/src/main/java/com/graphhopper/routing/profiles/MaxSpeed.java
  core/src/main/java/com/graphhopper/routing/profiles/MaxWeight.java
  core/src/main/java/com/graphhopper/routing/profiles/MaxWidth.java
  core/src/main/java/com/graphhopper/routing/profiles/SimpleBooleanEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/UnsignedDecimalEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/UnsignedIntEncodedValue.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/profiles/BooleanEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/profiles/DecimalEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactoryTest.java
  core/src/test/java/com/graphhopper/routing/profiles/IntEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/profiles/UnsignedDecimalEncodedValueTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/PtFlagEncoder.java
Labels: refactoring

#1640 Removes TraversalMode.EDGE_BASED_2DIR_UTURN
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/AbstractRoutingAlgorithm.java
  core/src/main/java/com/graphhopper/routing/Dijkstra.java
  core/src/main/java/com/graphhopper/routing/PathBidirRef.java
  core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedPathCH.java
  core/src/main/java/com/graphhopper/routing/ch/PreparationWeighting.java
  core/src/main/java/com/graphhopper/routing/ch/WitnessPathSearcher.java
  core/src/main/java/com/graphhopper/routing/util/TestAlgoCollector.java
  core/src/main/java/com/graphhopper/routing/util/TraversalMode.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
  core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionTest.java
  core/src/test/java/com/graphhopper/routing/AStarTest.java
  core/src/test/java/com/graphhopper/routing/AbstractRoutingAlgorithmTester.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionRefTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraOneToManyTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraTest.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHAlgoFactoryDecoratorTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/template/RoundTripRoutingTemplateTest.java
  core/src/test/java/com/graphhopper/routing/weighting/TurnWeightingTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/Isochrone.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
Labels: improvement, refactoring

#1649 Improve speed of elevation interpolation
  core/src/main/java/com/graphhopper/reader/dem/EdgeElevationInterpolator.java
  core/src/main/java/com/graphhopper/reader/dem/ElevationInterpolator.java
  core/src/main/java/com/graphhopper/reader/dem/NodeElevationInterpolator.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/main/java/com/graphhopper/util/BreadthFirstSearch.java
  core/src/main/java/com/graphhopper/util/DepthFirstSearch.java
  core/src/main/java/com/graphhopper/util/EngineWarmUp.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/main/java/com/graphhopper/util/XFirstSearch.java
  core/src/test/java/com/graphhopper/util/BreadthFirstSearchTest.java
  core/src/test/java/com/graphhopper/util/DepthFirstSearchTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
Labels: bug

#1577 Improve pointlist output for isochrone
  README.md
  core/files/changelog.txt
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/Isochrone.java
  web-api/src/main/java/com/graphhopper/http/WebHelper.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
  web/src/test/java/com/graphhopper/http/isochrone/IsochroneResourceTest.java
  web/src/test/java/com/graphhopper/http/isochrone/SPTResourceTest.java
Labels: improvement, web

#1641 Avoid main.js in git repo
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  core/files/changelog.txt
  core/files/docker-compose.yml
  docs/core/quickstart-from-source.md
  web/src/main/resources/assets/js/main.js
Labels: architecture, improvement
