Repository graphhopper/graphhopper, pull requests merged in 2020-06, with the labels that each got.

#2054 Use AStar by default for edge-based CH
  core/src/main/java/com/graphhopper/routing/AStarBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
  core/src/main/java/com/graphhopper/routing/ch/CHRoutingAlgorithmFactory.java
  core/src/main/java/com/graphhopper/routing/lm/LMRoutingAlgorithmFactory.java
Labels: performance

#2059 Make sure jersey errors are english
  pom.xml
Labels: test

#2065 Make virtual edge IDs consecutive
  core/src/main/java/com/graphhopper/routing/querygraph/EdgeChangeBuilder.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryOverlayBuilder.java
  core/src/main/java/com/graphhopper/routing/weighting/QueryGraphWeighting.java
  core/src/test/java/com/graphhopper/routing/HeadingResolverTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
Labels: refactoring

#1953 Improve resolution of elevation profiles with 3D Douglas Peucker and long edge sampling
  api/src/main/java/com/graphhopper/util/DistanceCalc.java
  api/src/main/java/com/graphhopper/util/DistanceCalcEarth.java
  api/src/main/java/com/graphhopper/util/Parameters.java
  api/src/test/java/com/graphhopper/util/DistanceCalcEarthTest.java
  config-example.yml
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/reader/DataReader.java
  core/src/main/java/com/graphhopper/reader/dem/AbstractElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/EdgeSampling.java
  core/src/main/java/com/graphhopper/reader/dem/ElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/MultiSourceElevationProvider.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/RouterConfig.java
  core/src/main/java/com/graphhopper/util/DistanceCalcEuclidean.java
  core/src/main/java/com/graphhopper/util/DouglasPeucker.java
  core/src/test/java/com/graphhopper/reader/dem/EdgeSamplingTest.java
  core/src/test/java/com/graphhopper/util/DistanceCalcEuclideanTest.java
  core/src/test/java/com/graphhopper/util/DouglasPeuckerTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphHopperGtfs.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperTest.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
Labels: improvement

#2069 Add new query graph for CH routing
  core/src/main/java/com/graphhopper/routing/AbstractBidirCHAlgo.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/AlternativeRouteCH.java
  core/src/main/java/com/graphhopper/routing/CHPathCalculator.java
  core/src/main/java/com/graphhopper/routing/DirectionResolver.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/ch/CHRoutingAlgorithmFactory.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedCHBidirPathExtractor.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedCHBidirPathExtractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareCHGraph.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/ch/ShortcutUnpacker.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryRoutingCHGraph.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIterator.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
  core/src/main/java/com/graphhopper/routing/util/TestAlgoCollector.java
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorState.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorStateImpl.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraph.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDFullIndex.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDFullWithEdgesIndex.java
  core/src/main/java/com/graphhopper/storage/index/Location2IDQuadtree.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
  core/src/main/java/com/graphhopper/util/CHEdgeExplorer.java
  core/src/main/java/com/graphhopper/util/CHEdgeIterator.java
  core/src/main/java/com/graphhopper/util/CHEdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/main/java/com/graphhopper/util/PathMerger.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteCHTest.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/QueryRoutingCHGraphTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GtfsReader.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
Labels: refactoring

#2073 Provide edge key PathDetails
  api/src/main/java/com/graphhopper/util/Parameters.java
  core/src/main/java/com/graphhopper/util/details/EdgeKeyDetails.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
Labels: new feature
