Repository graphhopper/graphhopper, pull requests merged in 2020-03, with the labels that each got.

#1936 access on private roads
  core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java
  core/src/test/java/com/graphhopper/routing/BidirPathExtractorTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DirectedBidirectionalDijkstraTest.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedWitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
  core/src/test/java/com/graphhopper/routing/profiles/DecimalEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/util/AbstractFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMTurnRelationParserTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  core/src/test/java/com/graphhopper/storage/TurnCostStorageTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
Labels: improvement

#1947 avoid IntsRef recreation and simpler getter
  core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
  core/src/test/java/com/graphhopper/storage/TurnCostStorageTest.java
Labels: refactoring

#1943 Simplify entire edges on import instead of just pillar nodes
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: improvement

#1950 Avoid graph dependency
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
  core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
  core/src/main/java/com/graphhopper/routing/weighting/BlockAreaWeighting.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/Graph.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
  core/src/test/java/com/graphhopper/routing/weighting/BlockAreaWeightingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
Labels: refactoring

#1894 Move SpatialRuleLookup benchmark into Measurement class
  benchmark/benchmark.sh
  core/src/main/java/com/graphhopper/util/MiniPerfTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  tools/pom.xml
  tools/src/main/java/com/graphhopper/tools/Measurement.java
Labels: architecture, performance

#1942 Bilinear interpolation for height tiles
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/reader/dem/AbstractElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/AbstractSRTMElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/AbstractTiffElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/ElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/GMTEDProvider.java
  core/src/main/java/com/graphhopper/reader/dem/HeightTile.java
  core/src/main/java/com/graphhopper/reader/dem/MultiSourceElevationProvider.java
  core/src/test/java/com/graphhopper/reader/dem/HeightTileTest.java
Labels: algorithm, improvement

#1944 Refactor distance calculation utilities to be elevation-aware
  api/src/main/java/com/graphhopper/util/DistanceCalc.java
  api/src/main/java/com/graphhopper/util/DistanceCalcEarth.java
  api/src/main/java/com/graphhopper/util/DistancePlaneProjection.java
  api/src/main/java/com/graphhopper/util/Helper.java
  api/src/main/java/com/graphhopper/util/PointList.java
  api/src/test/java/com/graphhopper/util/DistanceCalcEarthTest.java
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/reader/dem/EdgeElevationInterpolator.java
  core/src/main/java/com/graphhopper/util/DistanceCalcEuclidean.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/util/DistanceCalcEuclideanTest.java
  core/src/test/java/com/graphhopper/util/GHUtilityTest.java
  reader-gtfs/src/test/java/com/graphhopper/reader/gtfs/GraphExplorerTest.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
Labels: refactoring

#1928 GraphHopperServerConfiguration auto-detects available ports
  CONTRIBUTORS.md
  web/src/main/java/com/graphhopper/http/GraphHopperServerConfiguration.java
  web/src/test/java/com/graphhopper/http/GraphHopperLandmarksTest.java
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
  web/src/test/java/com/graphhopper/http/resources/ChangeGraphResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/GtfsTest.java
  web/src/test/java/com/graphhopper/http/resources/I18nResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/PtIsochroneTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceIssue1574Test.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
  web/src/test/java/com/graphhopper/http/util/GraphHopperServerTestConfiguration.java
  web/src/test/java/com/graphhopper/http/util/TestUtils.java
Labels: improvement, refactoring

#1954 use enum instead of int
  core/src/main/java/com/graphhopper/reader/dem/EdgeElevationInterpolator.java
  core/src/main/java/com/graphhopper/routing/DirectionResolver.java
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/InstructionsHelper.java
  core/src/main/java/com/graphhopper/routing/Path.java
  core/src/main/java/com/graphhopper/routing/querygraph/GraphModificationBuilder.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIterator.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
  core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
  core/src/main/java/com/graphhopper/storage/index/QueryResult.java
  core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/FetchMode.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsFromEdges.java
  core/src/test/java/com/graphhopper/reader/dem/BridgeElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  core/src/test/java/com/graphhopper/util/GHUtilityTest.java
  docs/core/create-new-flagencoder.md
  docs/core/low-level-api.md
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/TripFromLabel.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/WrapperGraph.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
  web-bundle/src/main/java/com/graphhopper/resources/MVTResource.java
Labels: refactoring

#1929 Mapzen (skadi) elevation provider
  NOTICE.md
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/reader/dem/AbstractSRTMElevationProvider.java
  core/src/main/java/com/graphhopper/reader/dem/SRTMGL1Provider.java
  core/src/main/java/com/graphhopper/reader/dem/SRTMProvider.java
  core/src/main/java/com/graphhopper/reader/dem/SkadiProvider.java
  core/src/test/java/com/graphhopper/reader/dem/SkadiProviderTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: new feature

#1956 refactor PMap to use string,object instead of string,string
  api/src/main/java/com/graphhopper/GHRequest.java
  api/src/main/java/com/graphhopper/GraphHopperConfig.java
  api/src/main/java/com/graphhopper/config/ProfileConfig.java
  api/src/main/java/com/graphhopper/routing/util/HintsMap.java
  api/src/main/java/com/graphhopper/util/Helper.java
  api/src/main/java/com/graphhopper/util/PMap.java
  api/src/test/java/com/graphhopper/util/PMapTest.java
  client-hc/src/main/java/com/graphhopper/api/GHMatrixAbstractRequester.java
  client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ProfileResolver.java
  core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/test/java/com/graphhopper/GraphHopperProfileConfigTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  core/src/test/java/com/graphhopper/routing/ch/CHProfileSelectorTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMProfileSelectorTest.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  core/src/test/java/com/graphhopper/routing/template/RoundTripRoutingTemplateTest.java
  core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphHopperGtfs.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/PtRouteResource.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/tools/QueryTorture.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
  web/src/main/java/com/graphhopper/http/GraphHopperApplication.java
  web/src/test/java/com/graphhopper/http/resources/ChangeGraphResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceIssue1574Test.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceWithEleTest.java
Labels: refactoring

#1959 Added more compass directions
  core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
Labels: improvement

#1964 Disable turn costs for LM preparation
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/AbstractNonCHBidirAlgo.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: bug

#1962 more PMap refactoring
  api/src/main/java/com/graphhopper/GraphHopperConfig.java
  api/src/main/java/com/graphhopper/routing/util/HintsMap.java
  api/src/main/java/com/graphhopper/util/PMap.java
  api/src/test/java/com/graphhopper/util/GHRequestTest.java
  client-hc/src/main/java/com/graphhopper/api/GraphHopperMatrixWeb.java
  core/src/main/java/com/graphhopper/routing/AlgorithmOptions.java
  core/src/main/java/com/graphhopper/routing/ProfileResolver.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  reader-gtfs/src/test/java/com/graphhopper/AnotherAgencyIT.java
  reader-gtfs/src/test/java/com/graphhopper/ExtendedRouteTypeIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperGtfsIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
  reader-gtfs/src/test/java/com/graphhopper/RealtimeIT.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web/src/test/java/com/graphhopper/http/GraphHopperLandmarksTest.java
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
  web/src/test/java/com/graphhopper/http/resources/ChangeGraphResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/GtfsTest.java
  web/src/test/java/com/graphhopper/http/resources/I18nResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/PtIsochroneTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceIssue1574Test.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
Labels: refactoring

#1963 improve Measurement for block_area
  .travis.yml
  benchmark/benchmark.sh
  tools/src/main/java/com/graphhopper/tools/Measurement.java
Labels: architecture, improvement

#1958 Move ProfileResolver out of GraphHopper class
  api/src/main/java/com/graphhopper/GHRequest.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java
  config-example.yml
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ProfileResolver.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/test/java/com/graphhopper/GraphHopperAPITest.java
  core/src/test/java/com/graphhopper/routing/ProfileResolverTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  core/src/test/java/com/graphhopper/routing/ch/CHProfileSelectorTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMProfileSelectorTest.java
  docs/web/api-doc.md
  reader-gtfs/src/test/java/com/graphhopper/AnotherAgencyIT.java
  reader-gtfs/src/test/java/com/graphhopper/ExtendedRouteTypeIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperGtfsIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
  reader-gtfs/src/test/java/com/graphhopper/RealtimeIT.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
  web/src/test/java/com/graphhopper/http/GraphHopperLandmarksTest.java
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
  web/src/test/java/com/graphhopper/http/resources/ChangeGraphResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/GpxTravelTimeConsistencyTest.java
  web/src/test/java/com/graphhopper/http/resources/GtfsTest.java
  web/src/test/java/com/graphhopper/http/resources/I18nResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/PtIsochroneTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceIssue1574Test.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceProfileSelectionTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTurnCostsTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
Labels: refactoring

#1977 remove change graph
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/storage/change/ChangeGraphHelper.java
  core/src/main/java/com/graphhopper/storage/change/ChangeGraphResponse.java
  core/src/test/java/com/graphhopper/GraphHopperAPITest.java
  core/src/test/java/com/graphhopper/storage/change/ChangeGraphHelperTest.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/resources/ChangeGraphResource.java
  web/src/test/java/com/graphhopper/http/resources/ChangeGraphResourceTest.java
Labels: refactoring
