Repository graphhopper/graphhopper, pull requests merged in 2020-11, with the labels that each got.

#2163 add turn cost example for Java API
  api/src/main/java/com/graphhopper/util/Helper.java
  api/src/test/java/com/graphhopper/util/HelperTest.java
  example/src/main/java/com/graphhopper/example/RoutingExampleTC.java
  example/src/test/java/com/graphhopper/example/RoutingExampleTest.java
Labels: documentation

#2148 Add a public facing Healthcheck
  core/src/main/java/com/graphhopper/GraphHopper.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/http/health/GraphHopperHealthCheck.java
  web-bundle/src/main/java/com/graphhopper/resources/HealthcheckResource.java
Labels: improvement, web

#2168 TransportationMode refactoring
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/TransportationMode.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMTurnRelationParser.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/AbstractSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleSet.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/AustriaSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/GermanySpatialRule.java
  core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMTurnRelationParserTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTSTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
Labels: refactoring

#2158 Details support for mtb_scale, mtb_uphill_scale, sac_scale and horse_scale
  config-example.yml
  core/src/main/java/com/graphhopper/routing/ev/HikeRating.java
  core/src/main/java/com/graphhopper/routing/ev/HorseRating.java
  core/src/main/java/com/graphhopper/routing/ev/MtbRating.java
  core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHikeRatingParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHorseRatingParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMtbRatingParser.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
Labels: new feature

#2167 Remove InstructionAnnotation
  api/src/main/java/com/graphhopper/util/FinishInstruction.java
  api/src/main/java/com/graphhopper/util/Instruction.java
  api/src/main/java/com/graphhopper/util/InstructionAnnotation.java
  api/src/main/java/com/graphhopper/util/RoundaboutInstruction.java
  api/src/main/java/com/graphhopper/util/ViaInstruction.java
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/test/java/com/graphhopper/util/InstructionListTest.java
  docs/web/api-doc.md
  reader-gtfs/src/main/java/com/graphhopper/gtfs/TripFromLabel.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperTest.java
  web-api/src/main/java/com/graphhopper/jackson/InstructionListSerializer.java
  web-api/src/main/java/com/graphhopper/jackson/ResponsePathDeserializer.java
  web-api/src/test/java/com/graphhopper/util/InstructionListRepresentationTest.java
  web-bundle/src/test/java/com/graphhopper/util/gpx/GpxFromInstructionsTest.java
  web/src/main/resources/assets/js/instructions.js
Labels: refactoring

#2174 Remove linkA/B fields from CH shortcuts
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedShortcutInserter.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedShortcutInserter.java
  core/src/main/java/com/graphhopper/routing/ch/NodeOrderingProvider.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
  core/src/main/java/com/graphhopper/util/Constants.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteCHTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/QueryRoutingCHGraphTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
Labels: performance

#2179 Update README to point to an actively maintained morituri fork
  README.md
Labels: documentation

#2180 move Java code from API documentation to code
  client-hc/README.md
  client-hc/pom.xml
  client-hc/src/main/java/com/graphhopper/api/GraphHopperMatrixWeb.java
  client-hc/src/test/java/com/graphhopper/api/Examples.java
  core/files/changelog.txt
Labels: documentation, web-api-client

#2190 Remove Activation dependency
  web/pom.xml
Labels: architecture

#2191 Avoid frequent polling in OSMInputFile
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMInputFile.java
Labels: performance

#2196 Minor refactoring for LocationIndexTree
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
Labels: refactoring

#2188 Refactor spatialrule border handling
  core/files/changelog.txt
  core/files/spatialrules/README.MD
  core/files/spatialrules/countries.geo.json
  core/files/spatialrules/countries.geojson
  core/src/main/java/com/graphhopper/routing/ev/Country.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/CountriesSpatialRuleFactory.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleContainer.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleFactory.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilder.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupHelper.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTS.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTSTest.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
Labels: improvement, refactoring
