Repository graphhopper/graphhopper, pull requests merged in 2020-07, with the labels that each got.

#2079 Change OpenJDK download server
  .travis.yml
Labels: architecture

#2077 Update core,client-hc and reader-osm to Java 8
  client-hc/pom.xml
  core/files/changelog.txt
  core/pom.xml
  reader-osm/pom.xml
Labels: architecture

#2071 Merge of navigation repository
  CONTRIBUTORS.md
  core/files/changelog.txt
  navigation/LICENSE.txt
  navigation/README.md
  navigation/pom.xml
  navigation/settings.xml
  navigation/src/main/java/com/graphhopper/navigation/DistanceConfig.java
  navigation/src/main/java/com/graphhopper/navigation/DistanceUtils.java
  navigation/src/main/java/com/graphhopper/navigation/NavigateResource.java
  navigation/src/main/java/com/graphhopper/navigation/NavigateResponseConverter.java
  navigation/src/main/java/com/graphhopper/navigation/NavigateResponseConverterTranslationMap.java
  navigation/src/main/java/com/graphhopper/navigation/VoiceInstructionConfig.java
  navigation/src/main/resources/com/graphhopper/navigation/de_DE.txt
  navigation/src/main/resources/com/graphhopper/navigation/en_US.txt
  navigation/src/test/java/com/graphhopper/navigation/NavigateResourceTest.java
  navigation/src/test/java/com/graphhopper/navigation/NavigateResponseConverterTest.java
  navigation/src/test/java/com/graphhopper/navigation/NavigateResponseConverterTranslationMapTest.java
  navigation/src/test/java/com/graphhopper/navigation/VoiceInstructionConfigTest.java
Labels: architecture, improvement, navigation

#2082 withInstructions should be without path details
  tools/src/main/java/com/graphhopper/tools/Measurement.java
Labels: architecture, improvement

#2075 Handle cycleway tag #2074
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
Labels: osm

#2090 Set Unit public
  navigation/src/main/java/com/graphhopper/navigation/DistanceUtils.java
Labels: navigation

#2087 Clean-up edge iterator classes
  core/src/main/java/com/graphhopper/routing/Path.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/EdgeAccess.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
Labels: refactoring

#2093 add isochrone to measurement
  benchmark/benchmark.sh
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/ContourBuilder.java
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/ShortestPathTree.java
  pom.xml
  tools/pom.xml
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
Labels: performance

#2094 fix bucket size
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
Labels: bug, isochrone

#2092 Work around slow PriorityQueue.remove
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/ShortestPathTree.java
  isochrone/src/test/java/com/graphhopper/isochrone/algorithm/ShortestPathTreeTest.java
Labels: isochrone, performance
