Repository graphhopper/graphhopper, pull requests merged in 2020-09, with the labels that each got.

#2114 Update default config file name in graphhopper.sh output
  graphhopper.sh
Labels: documentation

#2091 Improve tag extraction
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/helpers/OSMValueExtractor.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleSet.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/AustriaSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/GermanySpatialRule.java
  core/src/test/java/com/graphhopper/routing/util/AbstractFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMValueExtractorTest.java
  tools/src/main/java/com/graphhopper/tools/TagInfoUtil.java
Labels: improvement, osm

#2138 added missing BooleanDetails to PathDetailsBuilderFactory
  core/src/main/java/com/graphhopper/util/details/BooleanDetails.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: improvement
