Repository graphhopper/graphhopper, pull requests merged in 2020-05, with the labels that each got.

#2027 better estimate factor to store landmark weights more precise
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: algorithm, improvement

#2026 check profile if used for LM or CH preparation
  api/src/main/java/com/graphhopper/config/Profile.java
  api/src/main/java/com/graphhopper/routing/util/CustomModel.java
  api/src/main/java/com/graphhopper/util/Helper.java
  api/src/main/java/com/graphhopper/util/PMap.java
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ev/UnsignedIntEncodedValue.java
  core/src/main/java/com/graphhopper/storage/CHConfig.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
Labels: improvement

#2035 Clean up TarjanSCC's single-node component handling
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/main/java/com/graphhopper/routing/subnetwork/TarjansSCCAlgorithm.java
Labels: algorithm, performance

#2041 include npm as part of the maven cycle
  .gitignore
  .travis.yml
  config-example.yml
  core/files/changelog.txt
  docs/core/quickstart-from-source.md
  graphhopper.sh
  pom.xml
  web/package.json
  web/pom.xml
Labels: architecture, improvement, web

#2044 Use edge-based subnetwork removal if turn costs are enabled
  core/files/edge_based_subnetwork.osm.xml.gz
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
Labels: improvement

#2048 Add maven profiles to skip tools and shaded web jars
  tools/pom.xml
  web/pom.xml
Labels: improvement

#2049 Setup deployment on GitHub packages
  .github/workflows/push-packages.yml
  pom.xml
Labels: architecture
