Repository graphhopper/graphhopper, pull requests merged in 2020-01, with the labels that each got.

#1845 avoid skipping ways if mixing encoders in OSMRoadClassParser
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMBikeNetworkTagParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMFootNetworkTagParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatTunnelParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatWaterParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxHeightParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxLengthParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWidthParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadClassLinkParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadClassParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoundaboutParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMSurfaceParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMTollParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMTrackTypeParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/SpatialRuleParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/TagParser.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatTunnelParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatWaterParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadClassParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMSurfaceParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMTollParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMTrackTypeParserTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
Labels: bug

#1722 Alternative routes with node-based CH
  core/src/main/java/com/graphhopper/routing/AlternativeRouteCH.java
  core/src/main/java/com/graphhopper/routing/ch/CHRoutingAlgorithmFactory.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteCHTest.java
Labels: new feature

#1842 Work towards removing TurnWeighting
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionCH.java
  core/src/main/java/com/graphhopper/routing/DijkstraOneToMany.java
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/ch/CHProfileSelector.java
  core/src/main/java/com/graphhopper/routing/ch/CHWeighting.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedCHBidirPathExtractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareCHEdgeIteratorImpl.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/TestAlgoCollector.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractAdjustedWeighting.java
  core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
  core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
  core/src/main/java/com/graphhopper/routing/weighting/Weighting.java
  core/src/main/java/com/graphhopper/storage/CHProfile.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHProfileSelectorTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedWitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
  core/src/test/java/com/graphhopper/routing/weighting/BidirectionalRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/BlockAreaWeightingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/ShortFastestWeightingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphExplorer.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  web-bundle/src/main/java/com/graphhopper/resources/InfoResource.java
Labels: refactoring

#1844 Use road class to determine if a fork should have an instruction
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: improvement

#1356 Changed fullscreen button size
  web/src/main/resources/assets/css/style.css
  web/src/main/resources/assets/img/full-reverse.png
  web/src/main/resources/assets/img/full-reverse.svg
  web/src/main/resources/assets/img/full.png
  web/src/main/resources/assets/img/full.svg
Labels: improvement, web

#1850 Use RoutingCHGraph adapter for CH query algorithms
  core/src/main/java/com/graphhopper/routing/AStar.java
  core/src/main/java/com/graphhopper/routing/AStarBidirection.java
  core/src/main/java/com/graphhopper/routing/AStarBidirectionCH.java
  core/src/main/java/com/graphhopper/routing/AStarBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirCHAlgo.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/AbstractNonCHBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/AbstractRoutingAlgorithm.java
  core/src/main/java/com/graphhopper/routing/AlternativeRouteCH.java
  core/src/main/java/com/graphhopper/routing/Dijkstra.java
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionCH.java
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/DijkstraBidirectionRef.java
  core/src/main/java/com/graphhopper/routing/DijkstraOneToMany.java
  core/src/main/java/com/graphhopper/routing/ch/CHRoutingAlgorithmFactory.java
  core/src/main/java/com/graphhopper/routing/ch/CHWeighting.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedCHBidirPathExtractor.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedCHBidirPathExtractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareCHEdgeIteratorImpl.java
  core/src/main/java/com/graphhopper/routing/ch/ShortcutFilter.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/main/java/com/graphhopper/storage/CHEdgeFilter.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeExplorer.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIterator.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorImpl.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorState.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorStateImpl.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraph.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/ShortcutUnpacker.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteCHTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraOneToManyTest.java
  core/src/test/java/com/graphhopper/routing/DirectedBidirectionalDijkstraTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/weighting/BidirectionalRoutingTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/Isochrone.java
  tools/src/main/java/com/graphhopper/ui/DebugAStarBi.java
  tools/src/main/java/com/graphhopper/ui/DebugDijkstraBidirection.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
Labels: refactoring

#1749 Makes all tests pass for LM
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/AStarBidirection.java
  core/src/main/java/com/graphhopper/routing/AStarBidirectionCH.java
  core/src/main/java/com/graphhopper/routing/AStarBidirectionEdgeCHNoSOD.java
  core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/AlternativeRoute.java
  core/src/main/java/com/graphhopper/routing/lm/LMApproximator.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/lm/PerfectApproximator.java
  core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/weighting/BalancedWeightApproximator.java
  core/src/main/java/com/graphhopper/routing/weighting/BeelineWeightApproximator.java
  core/src/main/java/com/graphhopper/routing/weighting/WeightApproximator.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
  core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/RandomizedRoutingTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
Labels: algorithm, bug

#1861 Use Strings to add CH profiles to GraphBuilder
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHAlgoFactoryDecoratorTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedWitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
  core/src/test/java/com/graphhopper/routing/weighting/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/ShortFastestWeightingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
Labels: refactoring

#1870 Remove unused maxRetries mechanism in GraphHopper#calcPaths
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/RoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
Labels: refactoring

#1871 AverageSpeedDetails: avoid exception for short edges
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/util/details/AverageSpeedDetails.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
Labels: bug

#1868 Disable rezooming on intermediate point addition
  web/src/main/resources/assets/js/main-template.js
Labels: web

#1829 Use JTS to determine applicable spatial rules
  config-example.yml
  core/src/main/java/com/graphhopper/routing/util/spatialrules/AbstractSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/CountriesSpatialRuleFactory.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleContainer.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookup.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupArray.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilder.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupHelper.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTS.java
  core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTSTest.java
  docs/core/spatial-rules.md
  reader-osm/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
Labels: improvement

#1876 Improve picking up default graph
  config-example.yml
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/Path.java
  core/src/main/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactory.java
  core/src/main/java/com/graphhopper/routing/profiles/EnumEncodedValue.java
  core/src/main/java/com/graphhopper/routing/profiles/RouteNetwork.java
  core/src/main/java/com/graphhopper/routing/profiles/TurnCost.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMBikeNetworkTagParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMFootNetworkTagParser.java
  core/src/main/java/com/graphhopper/routing/weighting/DefaultTurnCostProvider.java
  core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/reader/dem/BridgeElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/routing/BidirPathExtractorTest.java
  core/src/test/java/com/graphhopper/routing/DirectedBidirectionalDijkstraTest.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/routing/profiles/EnumEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
Labels: bug
