Repository graphhopper/graphhopper, pull requests merged in 2020-10, with the labels that each got.

#2141 remove Dockerfile
  Dockerfile
  README.md
  core/files/changelog.txt
Labels: architecture, documentation

#2145 Add seconds to the ferry interpolation log
  core/src/main/java/com/graphhopper/GraphHopper.java
Labels: improvement

#2144 Add logs to .gitignore
  .gitignore
Labels: improvement

#2149 Update changelog about maxspeed
  core/files/changelog.txt
Labels: documentation, refactoring

#2135 Add no_entry to TurnRestrictions
  core/src/main/java/com/graphhopper/reader/OSMTurnRelation.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/resources/com/graphhopper/reader/osm/test-restrictions.xml
Labels: improvement

#2150 Add Graph#getEdgeIteratorStateForKey(edgeKey) and edgeState.getEdgeKey()
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryOverlayBuilder.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIterator.java
  core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/Graph.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/RealtimeFeed.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/WrapperGraph.java
  reader-gtfs/src/test/java/com/graphhopper/gtfs/GraphExplorerTest.java
Labels: improvement

#2153 Rename branch 2.0 to 2.x
  README.md
Labels: documentation

#2142 Added missing car4wd icon for web interface button
  web/src/main/resources/assets/img/car4wd.png
  web/src/main/resources/assets/img/car4wd.svg
Labels: web

#2143 move example code from docs into source code
  README.md
  docs/core/location-index.md
  docs/core/low-level-api.md
  docs/core/routing.md
  docs/core/technical.md
  docs/core/weighting.md
  docs/index.md
  docs/isochrone/java.md
  example/pom.xml
  example/src/main/java/com/graphhopper/example/IsochroneExample.java
  example/src/main/java/com/graphhopper/example/LocationIndexExample.java
  example/src/main/java/com/graphhopper/example/LowLevelAPIExample.java
  example/src/main/java/com/graphhopper/example/RoutingExample.java
  example/src/main/resources/log4j.xml
  example/src/test/java/com/graphhopper/example/LocationIndexExampleTest.java
  example/src/test/java/com/graphhopper/example/LowLevelAPIExampleTest.java
  example/src/test/java/com/graphhopper/example/RoutingExampleTest.java
  pom.xml
Labels: documentation

#2156 improve enum encoded values
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/ev/HazmatTunnel.java
  core/src/main/java/com/graphhopper/routing/ev/RoadAccess.java
  core/src/main/java/com/graphhopper/routing/ev/RoadClass.java
  core/src/main/java/com/graphhopper/routing/ev/RouteNetwork.java
  core/src/main/java/com/graphhopper/routing/ev/Surface.java
  core/src/main/java/com/graphhopper/routing/ev/TrackType.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMBikeNetworkTagParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMFootNetworkTagParser.java
  core/src/main/java/com/graphhopper/util/Constants.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
Labels: refactoring

#2157 MiniPerfTest: no subclassing, inject lambda instead
  core/src/main/java/com/graphhopper/util/MiniPerfTest.java
  reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
Labels: performance, refactoring

#2162 CustomWeighting: ensure Map is ordered
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/routing/util/CustomModel.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/PriorityCalculator.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/SpeedCalculator.java
  core/src/test/java/com/graphhopper/routing/util/CustomModelTest.java
  core/src/test/java/com/graphhopper/routing/weighting/CustomWeightingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/PriorityCalculatorTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/SpeedCalculatorTest.java
  example/src/main/java/com/graphhopper/example/RoutingExample.java
Labels: bug
