Repository graphhopper/graphhopper, pull requests merged in 2020-04, with the labels that each got.

#1983 Add config option `preparation_profile` to allow cross-querying in hybrid mode
  api/src/main/java/com/graphhopper/config/LMProfileConfig.java
  config-example.yml
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/test/java/com/graphhopper/GraphHopperProfileConfigTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTurnCostsTest.java
Labels: new feature

#1990 Improve docker image size
  Dockerfile
  appveyor.yml
  graphhopper.sh
Labels: architecture

#1997 Remove querytorture
  graphhopper.sh
  tools/src/main/java/com/graphhopper/tools/QueryTorture.java
  tools/src/test/java/com/graphhopper/tools/QueryTortureTest.java
Labels: architecture, refactoring

#1998 Upgrade to dropwizard 2.0.x
  pom.xml
Labels: architecture

#1989 iOS port: remove Java Runtime specifics
  api/src/main/java/com/graphhopper/util/Helper.java
  core/src/main/java/com/graphhopper/GraphHopper.java
Labels: ios

#2003 test client-hc routing without internet requirement
  client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperGeocodingIT.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceClientHCTest.java
Labels: architecture, improvement

#2014 timeout should propagate to OkHttp
  client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperWebTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceClientHCTest.java
Labels: test

#2011 Isochrones just by weight (rather than time or distance)
  isochrone/src/main/java/com/graphhopper/isochrone/algorithm/ShortestPathTree.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
Labels: new feature

#2018 remove legacy turn_costs for isochrone too
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
Labels: refactoring

#2022 Use transportation mode for getOffBike
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
Labels: improvement
