Repository graphhopper/graphhopper, pull requests merged in 2020-02, with the labels that each got.

#1838 location lookup based on Weighting additionally to access
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/DirectionResolver.java
  core/src/main/java/com/graphhopper/routing/template/AbstractRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/RoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/test/java/com/graphhopper/routing/DirectionResolverOnQueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/DirectionResolverTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  core/src/test/java/com/graphhopper/routing/template/RoundTripRoutingTemplateTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
Labels: improvement

#1882 Improve turn instructions when leaving the roads
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
Labels: improvement, navigation

#1891 Remove routing algorithm factory decorator abstraction
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactoryDecorator.java
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/ch/CHProfileSelector.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  core/src/test/java/com/graphhopper/routing/ch/CHPreparationHandlerTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMAlgoFactoryDecoratorTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMPreparationHandlerTest.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
Labels: refactoring

#1899 Use LMProfile instead of just Weighting for Landmark preparations
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/lm/LMProfile.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
  core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMPreparationHandlerTest.java
  core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
Labels: refactoring

#1913 Cleanup GraphHopper tests in preparation to profile parameter
  core/src/test/java/com/graphhopper/GraphHopperAPITest.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
Labels: refactoring

#1914 No longer enable CH by default in GraphHopper class
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/test/java/com/graphhopper/GraphHopperAPITest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
  core/src/test/java/com/graphhopper/routing/ch/CHPreparationHandlerTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMPreparationHandlerTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  docs/core/routing.md
  docs/web/api-doc.md
  reader-gtfs/README.md
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
  web/src/test/java/com/graphhopper/http/resources/ChangeGraphResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/GpxTravelTimeConsistencyTest.java
  web/src/test/java/com/graphhopper/http/resources/I18nResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
Labels: refactoring

#1918 no need to explicitely list the snake case methods
  config-example.yml
  core/files/changelog.txt
  web-api/src/main/java/com/graphhopper/jackson/GHRequestMixIn.java
  web-api/src/main/java/com/graphhopper/jackson/Jackson.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
Labels: refactoring

#1911 fix country rule ordering
  core/src/main/java/com/graphhopper/routing/profiles/Country.java
  core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
  core/src/main/java/com/graphhopper/routing/util/parsers/SpatialRuleParser.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/CountriesSpatialRuleFactory.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilder.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupHelper.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTS.java
  core/src/test/java/com/graphhopper/routing/util/parsers/SpatialRuleParserTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupHelperTest.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
Labels: bug

#1917 Fix problems with block_area
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/weighting/BlockAreaWeighting.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/test/java/com/graphhopper/routing/weighting/BlockAreaWeightingTest.java
  core/src/test/java/com/graphhopper/storage/GraphEdgeIdFinderTest.java
  core/src/test/java/com/graphhopper/storage/change/ChangeGraphHelperTest.java
  core/src/test/resources/com/graphhopper/storage/change/overlaydata1.json
  reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
Labels: bug

#1892 highway=path and bicycle=yes should not get speed for pushing section
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
Labels: improvement, osm

#1880 SpatialRule interface rework
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParser.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/AbstractSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/CountriesSpatialRuleFactory.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/DefaultSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/AustriaSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/GermanySpatialRule.java
  core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTSTest.java
  reader-osm/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
Labels: refactoring

#1935 Add 100m radius restriction to point hint matches
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
  core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
Labels: improvement
