Repository graphhopper/graphhopper, pull requests merged in 2021-06, with the labels that each got.

#2335 Consider max priority in CustomWeighting
  api/src/main/java/com/graphhopper/util/CustomModel.java
  api/src/test/java/com/graphhopper/util/CustomModelTest.java
  core/src/main/java/com/graphhopper/routing/DefaultWeightingFactory.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeighting.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelParserTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceCustomModelTest.java
Labels: bug

#2333 Include priority EncodedValue in CustomWeighting
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/PriorityCode.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/weighting/CurvatureWeighting.java
  core/src/main/java/com/graphhopper/routing/weighting/PriorityWeighting.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeightingHelper.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/routing/PriorityRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
  core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/HikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/MountainBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/WheelchairFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelParserTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceCustomModelTest.java
Labels: bug

#2348 Include BBox also if start and end are identical
  CHANGELOG.md
  api/src/main/java/com/graphhopper/ResponsePath.java
  web-api/src/main/java/com/graphhopper/jackson/ResponsePathSerializer.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: bug, web

#2345 make absolute barriers passable
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/WheelchairFlagEncoderTest.java
  core/src/test/resources/com/graphhopper/reader/osm/test-barriers.xml
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
Labels: improvement, osm

#2351 make possible to run query after quickstart
  CONTRIBUTORS.md
  docs/web/api-doc.md
Labels: documentation, improvement

#2340 Allow barrier kissing_gate with bicycle=yes for all bicycle profiles,…
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
Labels: improvement, osm
