Repository graphhopper/graphhopper, pull requests merged in 2021-05, with the labels that each got.

#2301 Make custom model box work with dragging markers, changing vehicle, adding points etc.
  web-bundle/src/main/resources/com/graphhopper/maps/js/main-template.js
Labels: web

#2256 Make LM preparation working with custom profiles
  core/src/main/java/com/graphhopper/routing/AbstractNonCHBidirAlgo.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/util/FiniteWeightFilter.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMIssueTest.java
  core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCCTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
Labels: bug, performance, refactoring

#2304 avoid regex in navigate module
  navigation/src/main/java/com/graphhopper/navigation/NavigateResource.java
Labels: bug

#2308 Rewrite and fix CustomModelParser#findMaxSpeed
  api/src/main/java/com/graphhopper/json/Statement.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java
  core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeighting.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelParserTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingTest.java
Labels: bug

#2309 map matching: properly access turn costs for virtual nodes
  map-matching/src/main/java/com/graphhopper/matching/MapMatching.java
Labels: bug

#2316 Remove GraphHopperAPI#load
  api/src/main/java/com/graphhopper/GraphHopperAPI.java
  client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
Labels: refactoring

#2310 Stop using junit 4's `@Theory` in FareTest
  reader-gtfs/src/test/java/com/graphhopper/gtfs/fare/FareTest.java
Labels: refactoring

#2317 Add lanes encoded value
  config-example.yml
  core/src/main/java/com/graphhopper/routing/ev/Lanes.java
  core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMLanesParser.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMLanesParserTest.java
Labels: new feature

#2303 Implementation of smoothness encoded value.
  config-example.yml
  core/src/main/java/com/graphhopper/routing/ev/DefaultEncodedValueFactory.java
  core/src/main/java/com/graphhopper/routing/ev/Smoothness.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMSmoothnessParser.java
  core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/MountainBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMSmoothnessParserTest.java
  docs/core/custom-models.md
  web-bundle/src/main/js/custom-model-editor/demo/index.html
Labels: new feature, osm

#2312 Stop using junit 4 class parameterization
  core/src/test/java/com/graphhopper/routing/AlternativeRouteTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  web/src/test/java/com/graphhopper/http/MapMatchingTest.java
Labels: refactoring

#2328 use custom_model parameter directly in GH Maps URL
  web-bundle/src/main/resources/com/graphhopper/maps/js/main-template.js
Labels: improvement

#2330 Maps: make export link working with custom model
  web-bundle/src/main/resources/com/graphhopper/maps/js/graphhopper/GHRequest.js
  web-bundle/src/main/resources/com/graphhopper/maps/js/instructions.js
  web-bundle/src/main/resources/com/graphhopper/maps/js/main-template.js
  web-bundle/src/main/resources/com/graphhopper/maps/js/map.js
Labels: improvement, web

#2326 Use bbox intersection logic for rectangles
  core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeightingHelper.java
  core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
  core/src/main/java/com/graphhopper/util/shapes/Polygon.java
Labels: performance
