Repository graphhopper/graphhopper, pull requests merged in 2021-09, with the labels that each got.

#2385 Remove InternalGraphEventListener
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/InternalGraphEventListener.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
Labels: refactoring

#2387 Cleanup CH iterators, remove CHGraph etc.
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationGraph.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedShortcutInserter.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedShortcutInserter.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/ch/ShortcutFilter.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryRoutingCHGraph.java
  core/src/main/java/com/graphhopper/routing/util/AllCHEdgesIterator.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraph.java
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/storage/CHStorage.java
  core/src/main/java/com/graphhopper/storage/CHStorageBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorImpl.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorState.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorStateImpl.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraph.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraphImpl.java
  core/src/main/java/com/graphhopper/util/CHEdgeExplorer.java
  core/src/main/java/com/graphhopper/util/CHEdgeIterator.java
  core/src/main/java/com/graphhopper/util/CHEdgeIteratorState.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/QueryRoutingCHGraphTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedWitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedWitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/util/AccessFilterTest.java
  core/src/test/java/com/graphhopper/storage/CHGraphImplTest.java
  core/src/test/java/com/graphhopper/storage/CHStorageTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  core/src/test/java/com/graphhopper/util/CHEdgeIteratorTest.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
Labels: refactoring

#2391 Remove EncodingManager from BaseGraph, cleanup nodes and edges header
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/util/Constants.java
Labels: refactoring

#2397 Improve coordinate precision
  core/src/main/java/com/graphhopper/util/Constants.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/QueryRoutingCHGraphTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
  reader-gtfs/src/test/java/com/graphhopper/AnotherAgencyIT.java
  reader-gtfs/src/test/java/com/graphhopper/FreeWalkIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
  web-api/src/main/java/com/graphhopper/util/Helper.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceClientHCTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java
Labels: improvement

#2406 introduce barrier=yes
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
Labels: improvement, osm

#2398 Remove Storable interface
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/subnetwork/SubnetworkStorage.java
  core/src/main/java/com/graphhopper/search/StringIndex.java
  core/src/main/java/com/graphhopper/storage/DataAccess.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/Storable.java
  core/src/main/java/com/graphhopper/storage/StorableProperties.java
  core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndex.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
Labels: improvement

#2399 Move nodes and edges storage out of BaseGraph
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/BaseGraphNodesAndEdges.java
  core/src/main/java/com/graphhopper/storage/CHStorage.java
  core/src/main/java/com/graphhopper/storage/GHNodeAccess.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorImpl.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorStateImpl.java
  core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
Labels: refactoring

#2414 country_rules: fix documentation in example config
  config-example.yml
  core/src/main/java/com/graphhopper/GraphHopper.java
Labels: documentation
