Repository graphhopper/graphhopper, pull requests merged in 2021-11, with the labels that each got.

#2458 Ignore too large mtb:scale values
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMtbRatingParser.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMtbRatingParserTest.java
Labels: bug

#2455 Load CH preparations in parallel
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
Labels: refactoring, performance

#2466 Remove RoadEnvironment.SHUTTLE_TRAIN
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/ev/RoadEnvironment.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParser.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParserTest.java
Labels: refactoring

#2468 Remove ferry argument from TagParser#handleWayTags
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/parsers/CountryParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMBikeNetworkTagParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMFootNetworkTagParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatTunnelParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatWaterParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHikeRatingParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMHorseRatingParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMLanesParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxHeightParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxLengthParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWidthParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMtbRatingParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadClassLinkParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadClassParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoundaboutParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMSmoothnessParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMSurfaceParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMTollParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMTrackTypeParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/TagParser.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatTunnelParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatWaterParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMLanesParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMtbRatingParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadClassParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMSmoothnessParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMSurfaceParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMTollParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMTrackTypeParserTest.java
Labels: refactoring

#2472 Use a point along the edge geometry to determine areas
  core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
Labels: improvement

#2475 Remove the ch.prepare.done flag and separate CH and LM profile versions
  core/src/main/java/com/graphhopper/GraphHopper.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
Labels: refactoring

#2471 Remove acceptWay optimization
  core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/test/java/com/graphhopper/reader/dem/BridgeElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/reader/dem/EdgeElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/reader/dem/TunnelElevationInterpolatorTest.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/routing/ev/DecimalEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
  core/src/test/java/com/graphhopper/routing/util/Bike2WeightFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/MotorcycleFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/MountainBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/WheelchairFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParserTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
  core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
Labels: refactoring
