Repository graphhopper/graphhopper, pull requests merged in 2021-12, with the labels that each got.

#2480 Fix HashMap related flaky tests
  CONTRIBUTORS.md
  core/src/main/java/com/graphhopper/search/StringIndex.java
Labels: improvement

#2473 signed EncodedValues
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/ev/DecimalEncodedValue.java
  core/src/main/java/com/graphhopper/routing/ev/DecimalEncodedValueImpl.java
  core/src/main/java/com/graphhopper/routing/ev/EnumEncodedValue.java
  core/src/main/java/com/graphhopper/routing/ev/HikeRating.java
  core/src/main/java/com/graphhopper/routing/ev/HorseRating.java
  core/src/main/java/com/graphhopper/routing/ev/IntEncodedValue.java
  core/src/main/java/com/graphhopper/routing/ev/IntEncodedValueImpl.java
  core/src/main/java/com/graphhopper/routing/ev/Lanes.java
  core/src/main/java/com/graphhopper/routing/ev/MaxAxleLoad.java
  core/src/main/java/com/graphhopper/routing/ev/MaxHeight.java
  core/src/main/java/com/graphhopper/routing/ev/MaxLength.java
  core/src/main/java/com/graphhopper/routing/ev/MaxSpeed.java
  core/src/main/java/com/graphhopper/routing/ev/MaxWeight.java
  core/src/main/java/com/graphhopper/routing/ev/MaxWidth.java
  core/src/main/java/com/graphhopper/routing/ev/MtbRating.java
  core/src/main/java/com/graphhopper/routing/ev/SimpleBooleanEncodedValue.java
  core/src/main/java/com/graphhopper/routing/ev/StringEncodedValue.java
  core/src/main/java/com/graphhopper/routing/ev/TurnCost.java
  core/src/main/java/com/graphhopper/routing/ev/UnsignedDecimalEncodedValue.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/util/details/AverageSpeedDetails.java
  core/src/test/java/com/graphhopper/routing/ev/BooleanEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/ev/DecimalEncodedValueImplTest.java
  core/src/test/java/com/graphhopper/routing/ev/DecimalEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/ev/DefaultEncodedValueFactoryTest.java
  core/src/test/java/com/graphhopper/routing/ev/IntEncodedValueImplTest.java
  core/src/test/java/com/graphhopper/routing/ev/IntEncodedValueTest.java
  core/src/test/java/com/graphhopper/routing/ev/MaxWeightTest.java
  core/src/test/java/com/graphhopper/routing/ev/UnsignedDecimalEncodedValueTest.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/PtEncodedValues.java
Labels: new feature

#2481 Remove CH from GraphHopperStorage, allow delta import of CHs
  CHANGELOG.md
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryRoutingCHGraph.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraph.java
  core/src/main/java/com/graphhopper/storage/RoutingCHGraphImpl.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteCHTest.java
  core/src/test/java/com/graphhopper/routing/AlternativeRouteEdgeCHTest.java
  core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/QueryRoutingCHGraphTest.java
  core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/RoutingCHGraphImplTest.java
  core/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/EdgeBasedWitnessPathSearcherTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/util/AccessFilterTest.java
  core/src/test/java/com/graphhopper/storage/CHStorageTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
  example/src/main/java/com/graphhopper/example/LowLevelAPIExample.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
  web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceCustomModelLMTest.java
Labels: new feature, refactoring

#2486 Remove NotThreadSafe and ProgressListener
  core/src/main/java/com/graphhopper/routing/RoutingAlgorithm.java
  core/src/main/java/com/graphhopper/util/Downloader.java
  core/src/main/java/com/graphhopper/util/NotThreadSafe.java
  core/src/main/java/com/graphhopper/util/ProgressListener.java
  core/src/main/java/com/graphhopper/util/Unzipper.java
Labels: refactoring

#2491 Use a fixed number of maximum visited nodes for node-based CH
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/ch/CHParameters.java
  core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/NodeContractor.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
Labels: performance
