Repository graphhopper/graphhopper, pull requests merged in 2021-04, with the labels that each got.

#2279 No more contributor license agreement
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
Labels: architecture, documentation, improvement

#2280 Always use edge-based subnetwork removal
  config-example.yml
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
Labels: improvement

#2265 Use restricted values for Bicycle Oneways
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
Labels: bug, osm

#2260 Update maps hot reload setup
  docs/core/quickstart-from-source.md
  web-bundle/package.json
  web-bundle/src/main/resources/com/graphhopper/maps/js/config/options.js
Labels: web

#2283 AlgorithmOptions: Remove weighting and builder
  core/src/main/java/com/graphhopper/routing/AlgorithmOptions.java
  core/src/main/java/com/graphhopper/routing/FlexiblePathCalculator.java
  core/src/main/java/com/graphhopper/routing/RoundTripRouting.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactory.java
  core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
  core/src/main/java/com/graphhopper/routing/lm/LMRoutingAlgorithmFactory.java
  core/src/main/java/com/graphhopper/routing/util/TestAlgoCollector.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/DirectedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
  core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoundTripRoutingTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMIssueTest.java
  core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
Labels: refactoring

#2287 Do not include empty vehicle in client hc for POST matrix requests
  client-hc/src/main/java/com/graphhopper/api/GHMatrixAbstractRequester.java
  client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
  client-hc/src/test/java/com/graphhopper/api/AbstractGHMatrixWebTester.java
  client-hc/src/test/java/com/graphhopper/api/GHMatrixBatchTest.java
  client-hc/src/test/java/com/graphhopper/api/GHMatrixSyncTest.java
  client-hc/src/test/java/com/graphhopper/api/GraphHopperWebTest.java
Labels: improvement, web-api-client

#2289 Split custom model docs into client and server parts, update to JSON
  docs/core/custom-models.md
  docs/core/profiles.md
  example/src/main/java/com/graphhopper/example/RoutingExample.java
  web-bundle/src/main/resources/com/graphhopper/maps/index.html
Labels: documentation

#2281 remove GraphHopper.setEncodingManager
  config-example.yml
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/util/DefaultFlagEncoderFactory.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/GraphHopperAPITest.java
  core/src/test/java/com/graphhopper/GraphHopperProfileTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHProfileSelectorTest.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  docs/core/create-new-flagencoder.md
  docs/core/routing.md
  example/src/main/java/com/graphhopper/example/IsochroneExample.java
  example/src/main/java/com/graphhopper/example/LocationIndexExample.java
  example/src/main/java/com/graphhopper/example/LowLevelAPIExample.java
  example/src/main/java/com/graphhopper/example/RoutingExample.java
  example/src/main/java/com/graphhopper/example/RoutingExampleTC.java
  navigation/src/test/java/com/graphhopper/navigation/NavigateResponseConverterTest.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/GraphHopperGtfs.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
  web-bundle/src/main/java/com/graphhopper/resources/MapMatchingResource.java
  web/src/test/java/com/graphhopper/http/MapMatching2Test.java
  web/src/test/java/com/graphhopper/http/MapMatchingTest.java
  web/src/test/java/com/graphhopper/http/RoutingAdditivityTest.java
  web/src/test/java/com/graphhopper/http/resources/GpxTravelTimeConsistencyTest.java
Labels: refactoring

#2291 Remove GraphHopper#loadGraph and Princeton performance test
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/test/java/com/graphhopper/GraphHopperAPITest.java
  core/src/test/java/com/graphhopper/reader/PrincetonReader.java
  core/src/test/java/com/graphhopper/reader/PrincetonReaderTest.java
  core/src/test/java/com/graphhopper/routing/HeadingRoutingTest.java
  core/src/test/resources/com/graphhopper/reader/10000EWD.txt.gz
  core/src/test/resources/com/graphhopper/reader/mediumEWD.txt.gz
  core/src/test/resources/com/graphhopper/reader/tinyEWD.txt
  reader-osm/src/test/java/com/graphhopper/GraphHopperTest.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
Labels: refactoring

#2293 Refactor RoutingAlgorithmWithOSMTest
  core/src/main/java/com/graphhopper/routing/FlexiblePathCalculator.java
  core/src/main/java/com/graphhopper/routing/util/TestAlgoCollector.java
  reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
Labels: refactoring

#2294 Rename: DefaultEdgeFilter -> AccessFilter
  core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
  core/src/main/java/com/graphhopper/routing/ch/ShortcutFilter.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/main/java/com/graphhopper/routing/util/AccessFilter.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMTurnRelationParser.java
  core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorImpl.java
  core/src/main/java/com/graphhopper/storage/index/LocationIndex.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/routing/DirectionResolverOnQueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/DirectionResolverTest.java
  core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
  core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
  core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
  core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCCTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/TarjanSCCTest.java
  core/src/test/java/com/graphhopper/routing/util/AccessFilterTest.java
  core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
  core/src/test/java/com/graphhopper/routing/util/WheelchairFlagEncoderTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/GraphEdgeIdFinderTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
  core/src/test/java/com/graphhopper/util/CHEdgeIteratorTest.java
  core/src/test/java/com/graphhopper/util/DepthFirstSearchTest.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/GraphExplorer.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/GraphHopperGtfs.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/GtfsReader.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouterImpl.java
  reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
  web-bundle/src/main/java/com/graphhopper/resources/PtIsochroneResource.java
Labels: refactoring

#2295 Clean up PrepareRoutingSubnetwork and tests
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCC.java
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/test/java/com/graphhopper/routing/RoundTripRoutingTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCCTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
Labels: refactoring

#2297 use locationtech in isochrone instead of mapbox-vector-tile
  isochrone/pom.xml
  pom.xml
  web-bundle/pom.xml
Labels: architecture

#2290 Add Subnetwork EncodedValue; create separate subnetworks for each profile
  core/files/changelog.txt
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/ev/DefaultEncodedValueFactory.java
  core/src/main/java/com/graphhopper/routing/ev/Subnetwork.java
  core/src/main/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCC.java
  core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
  core/src/main/java/com/graphhopper/routing/util/DefaultSnapFilter.java
  core/src/test/java/com/graphhopper/routing/HeadingRoutingTest.java
  core/src/test/java/com/graphhopper/routing/RoundTripRoutingTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCCTest.java
  core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
  example/src/main/java/com/graphhopper/example/IsochroneExample.java
  map-matching/src/main/java/com/graphhopper/matching/MapMatching.java
  reader-osm/src/test/java/com/graphhopper/GraphHopperTest.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceCustomModelLMTest.java
  web/src/test/java/com/graphhopper/http/resources/RouteResourceCustomModelTest.java
Labels: improvement, refactoring

#2298 Move the reader-osm module into core
  .gitignore
  NOTICE.md
  README.md
  core/files/changelog.txt
  core/pom.xml
  core/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/Junit4To5Assertions.java
  core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
  core/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
  core/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops2.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops3.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops4.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-barriers.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-conditional-turn-restrictions.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-multi-profile-turn-restrictions.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-multiple-conditional-turn-restrictions.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm-negative-ids.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm-waterway.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm10.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm2.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm3.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm4.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm5.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm6.pbf
  core/src/test/resources/com/graphhopper/reader/osm/test-osm6.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm7.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm8.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-osm9.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-restrictions.xml
  core/src/test/resources/com/graphhopper/reader/osm/test-road-attributes.xml
  example/pom.xml
  map-matching/pom.xml
  navigation/pom.xml
  pom.xml
  reader-gtfs/pom.xml
  reader-osm/files/dem140191
  reader-osm/files/dem142188
  reader-osm/pom.xml
  reader-osm/src/test/resources/com/graphhopper/reader/osm/test-osm6.xml
  reader-osm/src/test/resources/com/graphhopper/reader/osm/test-osm7.xml
  tools/pom.xml
  web-bundle/pom.xml
Labels: refactoring

#2299 upgrade some dependencies
  pom.xml
Labels: architecture
