Repository graphhopper/graphhopper, pull requests merged in 2021-10, with the labels that each got.

#2411 Consider heading when snapping
  core/src/main/java/com/graphhopper/routing/HeadingResolver.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/ViaRouting.java
  core/src/main/java/com/graphhopper/routing/util/HeadingEdgeFilter.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/routing/HeadingRoutingTest.java
Labels: improvement

#2419 use jdk17 ga and jdk18 ea
  .travis.yml
  core/src/main/java/com/graphhopper/util/TranslationMap.java
  core/src/test/java/com/graphhopper/util/TranslationMapTest.java
Labels: improvement, architecture

#2421 Remove DataAccess#setSegmentSize
  core/src/main/java/com/graphhopper/search/StringIndex.java
  core/src/main/java/com/graphhopper/storage/AbstractDataAccess.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/BaseGraphNodesAndEdges.java
  core/src/main/java/com/graphhopper/storage/CHStorage.java
  core/src/main/java/com/graphhopper/storage/DataAccess.java
  core/src/main/java/com/graphhopper/storage/Directory.java
  core/src/main/java/com/graphhopper/storage/GHDirectory.java
  core/src/main/java/com/graphhopper/storage/MMapDataAccess.java
  core/src/main/java/com/graphhopper/storage/RAMDataAccess.java
  core/src/main/java/com/graphhopper/storage/RAMIntDataAccess.java
  core/src/main/java/com/graphhopper/storage/StorableProperties.java
  core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
  core/src/test/java/com/graphhopper/search/StringIndexTest.java
  core/src/test/java/com/graphhopper/storage/CHStorageTest.java
  core/src/test/java/com/graphhopper/storage/DataAccessTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
  core/src/test/java/com/graphhopper/storage/MMapDataAccessTest.java
  core/src/test/java/com/graphhopper/storage/RAMDataAccessTest.java
  core/src/test/java/com/graphhopper/storage/RAMIntDataAccessTest.java
Labels: refactoring

#2420 Don't ignore parsed access
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParser.java
Labels: bug

#2448 Extract WaySegmentParser from OSMReader
  core/src/main/java/com/graphhopper/reader/osm/OSMNodeData.java
  core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  core/src/main/java/com/graphhopper/reader/osm/SegmentNode.java
  core/src/main/java/com/graphhopper/reader/osm/WaySegmentParser.java
  core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
Labels: refactoring
