Repository graphhopper/graphhopper, pull requests merged in 2021-07, with the labels that each got.

#2355 Remove FlagEncoder#getVersion
  CHANGELOG.md
  core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/Car4WDFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
  core/src/main/java/com/graphhopper/storage/StorableProperties.java
  core/src/main/java/com/graphhopper/util/Constants.java
  core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
Labels: refactoring

#2367 Remove some outdated mentions of the DataFlagEncoder
  config-example.yml
  core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
  docs/core/spatial-rules.md
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
Labels: documentation, refactoring

#2370 avoid prototype pollution
  web-bundle/src/main/resources/com/graphhopper/maps/js/tools/url.js
  web-bundle/src/test/resources/com/graphhopper/maps/spec/tools/urlSpec.js
Labels: bug, security, web

#2371 Avoid "bicycle=use_sidepath" ways instead of preferring it.
  core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
  core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
Labels: improvement, osm

#2372 Move api module into web-api, remove Jackson MixIns
  CHANGELOG.md
  api/pom.xml
  core/pom.xml
  core/src/main/java/com/graphhopper/GraphHopperConfig.java
  core/src/main/java/com/graphhopper/config/LMProfile.java
  core/src/main/java/com/graphhopper/config/Profile.java
  core/src/test/java/com/graphhopper/GraphHopperProfileTest.java
  pom.xml
  web-api/pom.xml
  web-api/src/main/java/com/graphhopper/GHRequest.java
  web-api/src/main/java/com/graphhopper/GHResponse.java
  web-api/src/main/java/com/graphhopper/GraphHopperAPI.java
  web-api/src/main/java/com/graphhopper/ResponsePath.java
  web-api/src/main/java/com/graphhopper/Trip.java
  web-api/src/main/java/com/graphhopper/jackson/GHRequestMixIn.java
  web-api/src/main/java/com/graphhopper/jackson/GraphHopperModule.java
  web-api/src/main/java/com/graphhopper/jackson/LMProfileMixIn.java
  web-api/src/main/java/com/graphhopper/jackson/ProfileMixIn.java
  web-api/src/main/java/com/graphhopper/json/Statement.java
  web-api/src/main/java/com/graphhopper/util/CustomModel.java
  web-api/src/main/java/com/graphhopper/util/FinishInstruction.java
  web-api/src/main/java/com/graphhopper/util/Helper.java
  web-api/src/main/java/com/graphhopper/util/Instruction.java
  web-api/src/main/java/com/graphhopper/util/InstructionList.java
  web-api/src/main/java/com/graphhopper/util/JsonFeature.java
  web-api/src/main/java/com/graphhopper/util/JsonFeatureCollection.java
  web-api/src/main/java/com/graphhopper/util/NumHelper.java
  web-api/src/main/java/com/graphhopper/util/PMap.java
  web-api/src/main/java/com/graphhopper/util/Parameters.java
  web-api/src/main/java/com/graphhopper/util/PointAccess.java
  web-api/src/main/java/com/graphhopper/util/PointList.java
  web-api/src/main/java/com/graphhopper/util/RoundaboutInstruction.java
  web-api/src/main/java/com/graphhopper/util/ShallowImmutablePointList.java
  web-api/src/main/java/com/graphhopper/util/Translation.java
  web-api/src/main/java/com/graphhopper/util/ViaInstruction.java
  web-api/src/main/java/com/graphhopper/util/details/PathDetail.java
  web-api/src/main/java/com/graphhopper/util/exceptions/ConnectionNotFoundException.java
  web-api/src/main/java/com/graphhopper/util/exceptions/DetailedIllegalArgumentException.java
  web-api/src/main/java/com/graphhopper/util/exceptions/DetailedRuntimeException.java
  web-api/src/main/java/com/graphhopper/util/exceptions/GHException.java
  web-api/src/main/java/com/graphhopper/util/exceptions/PointDistanceExceededException.java
  web-api/src/main/java/com/graphhopper/util/exceptions/PointNotFoundException.java
  web-api/src/main/java/com/graphhopper/util/exceptions/PointOutOfBoundsException.java
  web-api/src/main/java/com/graphhopper/util/shapes/GHPoint.java
  web-api/src/main/java/com/graphhopper/util/shapes/GHPoint3D.java
  web-api/src/test/java/com/graphhopper/util/CustomModelTest.java
  web-api/src/test/java/com/graphhopper/util/FinishInstructionTest.java
  web-api/src/test/java/com/graphhopper/util/GHRequestTest.java
  web-api/src/test/java/com/graphhopper/util/GHResponseTest.java
  web-api/src/test/java/com/graphhopper/util/HelperTest.java
  web-api/src/test/java/com/graphhopper/util/PMapTest.java
  web-api/src/test/java/com/graphhopper/util/shapes/GHPoint3DTest.java
  web-api/src/test/java/com/graphhopper/util/shapes/GHPointTest.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/jackson/GraphHopperConfigMixIn.java
  web-bundle/src/main/java/com/graphhopper/jackson/GraphHopperConfigModule.java
  web-bundle/src/test/java/com/graphhopper/jackson/GraphHopperConfigModuleTest.java
Labels: refactoring

#2353 Replace spatial rules by custom areas, include country borders in bundle and add Country EncodedValue
  CHANGELOG.md
  README.md
  benchmark/benchmark.sh
  config-example.yml
  core/files/spatialrules/README.MD
  core/files/spatialrules/countries.geojson
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
  core/src/main/java/com/graphhopper/routing/ev/Country.java
  core/src/main/java/com/graphhopper/routing/ev/DefaultEncodedValueFactory.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
  core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
  core/src/main/java/com/graphhopper/routing/lm/SplitArea.java
  core/src/main/java/com/graphhopper/routing/util/AreaIndex.java
  core/src/main/java/com/graphhopper/routing/util/CustomArea.java
  core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
  core/src/main/java/com/graphhopper/routing/util/countryrules/AustriaCountryRule.java
  core/src/main/java/com/graphhopper/routing/util/countryrules/CountryRule.java
  core/src/main/java/com/graphhopper/routing/util/countryrules/CountryRuleFactory.java
  core/src/main/java/com/graphhopper/routing/util/countryrules/GermanyCountryRule.java
  core/src/main/java/com/graphhopper/routing/util/parsers/CountryParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParser.java
  core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParser.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/AbstractSpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/CountriesSpatialRuleFactory.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRule.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleContainer.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookup.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilder.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTS.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleSet.java
  core/src/main/java/com/graphhopper/routing/util/spatialrules/countries/AustriaSpatialRule.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/main/resources/com/graphhopper/countries/countries.geojson
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
  core/src/test/java/com/graphhopper/routing/util/countryrules/CountryRuleTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxSpeedParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParserTest.java
  core/src/test/java/com/graphhopper/routing/util/parsers/SpatialRuleParserTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/AreaIndexTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
  core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTSTest.java
  core/src/test/resources/com/graphhopper/reader/osm/test-osm11.xml
  docs/core/custom-areas-and-country-rules.md
  docs/core/spatial-rules.md
  docs/index.md
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
Labels: new feature, refactoring

#2376 Make larger shortcut weight possible
  core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
  core/src/main/java/com/graphhopper/util/CHEdgeIteratorState.java
  core/src/test/java/com/graphhopper/storage/CHGraphImplTest.java
  core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
Labels: bug, refactoring
