Repository graphhopper/graphhopper, pull requests merged in 2022-06, with the labels that each got.

#2600 Use separate deleted flag for SPTEntry, prevent exception when calculating routes with non-feasible approximator
  core/src/main/java/com/graphhopper/routing/SPTEntry.java
  core/src/test/java/com/graphhopper/routing/AStarBidirectionTest.java
  map-matching/src/main/java/com/graphhopper/matching/MapMatching.java
Labels: bug

#2591 Fix inconsistent took
  core/src/main/java/com/graphhopper/util/StopWatch.java
  web-api/src/main/java/com/graphhopper/jackson/ResponsePathSerializer.java
  web-bundle/src/main/java/com/graphhopper/resources/MapMatchingResource.java
  web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
Labels: web

#2606 Remove GraphHopperStorage
  core/src/main/java/com/graphhopper/GraphHopper.java
  core/src/main/java/com/graphhopper/routing/Router.java
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
  core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
  core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
  core/src/main/java/com/graphhopper/routing/util/VehicleTagParser.java
  core/src/main/java/com/graphhopper/storage/BaseGraph.java
  core/src/main/java/com/graphhopper/storage/CHStorage.java
  core/src/main/java/com/graphhopper/storage/CHStorageBuilder.java
  core/src/main/java/com/graphhopper/storage/GHNodeAccess.java
  core/src/main/java/com/graphhopper/storage/GraphBuilder.java
  core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
  core/src/main/java/com/graphhopper/util/GHUtility.java
  core/src/test/java/com/graphhopper/GraphHopperTest.java
  core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
  core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
  core/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
  core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
  core/src/test/java/com/graphhopper/storage/BaseGraphTest.java
  core/src/test/java/com/graphhopper/storage/BaseGraphWithTurnCostsTest.java
  core/src/test/java/com/graphhopper/storage/CHStorageTest.java
  example/src/main/java/com/graphhopper/example/IsochroneExample.java
  example/src/main/java/com/graphhopper/example/LowLevelAPIExample.java
  map-matching/src/main/java/com/graphhopper/matching/MapMatching.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/GraphHopperGtfs.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/GtfsReader.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/PtLocationSnapper.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouterFreeWalkImpl.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouterImpl.java
  reader-gtfs/src/main/java/com/graphhopper/gtfs/RealtimeFeed.java
  reader-gtfs/src/test/java/com/graphhopper/AnotherAgencyIT.java
  reader-gtfs/src/test/java/com/graphhopper/ExtendedRouteTypeIT.java
  reader-gtfs/src/test/java/com/graphhopper/FreeWalkIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperGtfsIT.java
  reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
  reader-gtfs/src/test/java/com/graphhopper/RealtimeIT.java
  tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
  tools/src/main/java/com/graphhopper/tools/Measurement.java
  tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
  web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
  web-bundle/src/main/java/com/graphhopper/http/RealtimeFeedLoadingCache.java
  web-bundle/src/main/java/com/graphhopper/http/health/GraphHopperHealthCheck.java
  web-bundle/src/main/java/com/graphhopper/resources/InfoResource.java
  web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/MVTResource.java
  web-bundle/src/main/java/com/graphhopper/resources/PtIsochroneResource.java
  web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
  web/src/test/java/com/graphhopper/application/MapMatching2Test.java
  web/src/test/java/com/graphhopper/application/MapMatchingTest.java
Labels: refactoring

#2612 Increase maximum edge-based CH key for preparation to 2^30 again
  core/src/main/java/com/graphhopper/routing/ch/CHPreparationGraph.java
Labels: bug

#2619 Remove FlagEncoder#getMaxSpeed()
  core/src/main/java/com/graphhopper/routing/util/DefaultFlagEncoderFactory.java
  core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
  core/src/main/java/com/graphhopper/routing/util/VehicleEncodedValues.java
  core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
  core/src/test/java/com/graphhopper/routing/PathTest.java
  core/src/test/java/com/graphhopper/routing/PriorityRoutingTest.java
  core/src/test/java/com/graphhopper/routing/util/FootTagParserTest.java
  core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelParserTest.java
  core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingTest.java
  core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
Labels: refactoring
